### ISSUE TITLE
Viewing and exporting monitored data

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-product-design#100]
**Overview**

Currently, the way data is displayed in the dashboard is not very clear. On the one hand there is the inspect data tab, on the other the monitoring tab. Secondly, there is no way to export data belonging to a single survey but in different forms. Thirdly, it is unclear how we should deal with forms that have been filled in multiple times, such as with water quality.

**A short overview of what we try to accomplish**

The aim is to improve the Monitoring feature and bring it the expected and needed functions mostly on the dashboard. In order to do so we will:
1) create 4/5 use cases based on real projects to understand the different types of users, how they work with the app and the dashboard and what type of information/data do they want to see, so how do they work with the Monitoring feature 
2) Define what kinds of views / reports (both on the dashboard, and in excel reports) would users need.
3) Define how the user works with the app - viewing the forms, data sets, etc. 

**Non goals**
In this stage we will not be dealing with the more complex data features as geoshapes, because we want to create a solid way of viewing and exporting monitored data.

**Links to documents**
- User stories and user cases: http://bit.ly/1JXWHka
- Functional design - https://github.com/akvo/akvo-product-design/blob/master/FLOW/Features/100-monitored-data-export/FunctionalDesign.md

**Comment by iperdomo** [comment]
Issue # 100, nice!

It is not clear how to export/visualize/show repeatable question groups.

cc/ @ichinaski

**Comment by janagombitova** [comment]
Linked to #44

**Comment by janagombitova** [comment]
Need to break down this issue into smaller parts (respective issues from FLOW repository):
1. Viewing collected data on the dashboard
2. Reporting

**Comment by janagombitova** [comment]
As this work will be part of #70 - closing the issue
