### ISSUE TITLE
Report on indicators

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-product-design#101]
Needs further discussion
- Ability for users to report on indicators through RSR
- Use pre-formatted updates
- to be able to give annual / mid-year summary

**Comment by KasperBrandt** [comment]
@lauraroverts Not sure about the annual / mid-year summary in this one, but I assume that "reporting on indicators" means that it should be possible to update an indicator from an RSR update. Is that correct?

**Comment by lauraroverts** [comment]
Not sure if it will be through an RSR update, but it needs to be possible to update the numbers that belong to an indicator (= reporting on indicators). Also in the end it needs to be possible to export a report and visualisations of the data about a certain timeframe.

**Comment by loicsans** [comment]
I has to be possible to update indicators values through an RSR update...

**Comment by stellanl** [comment]
It does seem natural that an update and a change in indicators go together. Just poking at the indicators is a "minimalist" kind of report. Maybe it would be good if the user had the opportunity/was forced to elaborate?
