### ISSUE TITLE
Small user interface enhancements

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-product-design#104]
Below you'll find a list of small enhancements that need to be changed. 

1) Change 'Update list' into 'Search'
2) At financial overview of a project, e.g. http://rsr.akvo.org/en/project/790/finance/
- remove decimals: no need to display cents
- Add 'total amount funded' 
- Add project's budget start- and end dates

![screen shot 2015-06-03 at 11 33 29](https://cloud.githubusercontent.com/assets/4179989/7957013/8fe62b16-09e4-11e5-841f-2fc79bd58fb3.png)

3) Show full data report, e.g. http://rsr.akvo.org/en/project/790/report/
- Look at alignment: e.g. participating organisations not in line underneath each other
- 'Target group' --> not visible at project page. Important to add
- 'Current situation' --> sounds confusive. Current means 'today' so then this info would need to change everyday. Therefore change 'current situation' in 'Situation at start of project' or something like that
- Under 'product budget items' --> add the description for items that are labeled with 'other 1', 'other 2' etc. 
- Add 'Export data' button where you can also 'print this page'

4) At project page add visual to show what is the total project budget amount and how much money is needed if there is a donate button, like at project overview. 
![screen shot 2015-06-03 at 12 16 44](https://cloud.githubusercontent.com/assets/4179989/7957830/9ad93c74-09ea-11e5-9b05-7a76c9e50582.png)
 vs 
![screen shot 2015-06-03 at 12 16 58](https://cloud.githubusercontent.com/assets/4179989/7957831/9d6cc794-09ea-11e5-9528-1117706f0ece.png)

5) Add 'Indicators' to 'Results', since this field shows 'Results & Indicators'
![Uploading Screen Shot 2015-06-03 at 13.06.56.png…]()

6) When writing a project update: when you want to start a new paragraph hitting the 'enter' key, you can continue typing on the next line (backend). However, at a project update (frontend), it doesn't start at a new paragraph. See http://rsr.akvo.org/en/admin/rsr/projectupdate/9876/ vs http://rsr.akvo.org/en/project/2241/update/9876/

7) Users with a small computer screen, only see "Upd.." instead of "Update". 
![screenshot 3](https://cloud.githubusercontent.com/assets/4179989/8006640/01bca2da-0b96-11e5-9f48-c3dc9fe03737.png)

8) Replace the text in http://rsr.akvo.org/en/myrsr/iati/ with: "IATI stands for International Aid Transparency Initiative, which is a global reporting standard that makes it possible to compare and compile data sets from different projects and organisations. On this page it is possible to export an IATI file of the projects of your organisation or view previously exported files. Since your account is connected to multiple organisations, please select an organisation first."

**Comment by gabemart** [comment]
@lauraroverts When removing decimals on the project financial overview, am I correct that this is just for the "project financial details" section? (i.e. just where the decimals are crossed out in the mockup?)

**Comment by lauraroverts** [comment]
@gabe, all decimals should be removed, so also in the "donations", "current funders" and "project funding" sections.

**Comment by gabemart** [comment]
@lauraroverts OK, so we just round donations etc. to the nearest whole number?

**Comment by lauraroverts** [comment]
yes please

**Comment by lauraroverts** [comment]
Was released in Akvo RSR version 3.4 Honiara
