### ISSUE TITLE
Translate feature Akvo Pages

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-product-design#106]
A translate feature for Akvo Pages is needed to translate all static project information. Like what was possible in RSR 2.0. 

This feature is a very powerful for demos and sales. Several partners have been requesting getting this back in place, like the Dutch embassy in Mozambique.  

![untitled](https://cloud.githubusercontent.com/assets/4179989/7981244/ebcacee0-0aad-11e5-831e-dc56d31318f8.png)

**Comment by kardan** [comment]
@loicsans we will need UX/UI work on how to deal with two sets of language pickers.

**Comment by lauraroverts** [comment]
Has been released Akvo RSR version 3.4 Honiara
