### ISSUE TITLE
Lookup question

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-product-design#110]
### Overview

The look-up question creates relationships between two self standing data sets, two different surveys. When you create a relationship, you tell FLOW to link a record/question field in one form to another record in another form. This relation then links the collected data, which is still stored in two different data sets.

Look up question is the new question option we will be adding to FLOW.

**How does this work?**

Assume that you have project where you monitor biogas installations, which are built around the country by different construction companies. You create a monitoring survey for biogas installations. This survey contains the registration form and the monitoring form. In the registration form you enter the basic details of the biogas installation and which company constructed the installation. When you enter the details, you find that one or more installations were build by the same company and you have to enter the company name, again and again. This leads to duplication of information and ineffective data collection. In order to avoid this, you will create another survey called Construction Companies to hold information of all the companies and create a relationship between the Company Information form and the Biogas registration form. To create this relationship, you just add a look-up field in the Biogas registration form to import data from the field Construction company name in the Company Information form in the Construction Companies survey.The lookup field will lookup the ID of the record in the source form and it will display a dropdown menu containing items from the source form.
#### Initial features:
1. Lookup question type and settings dialogue 
2. App - saving the referenced list from the 2nd form and showing it as options in the look up question
3. Viewing the selected option or options, when inspecting collected data on the dashboard
4. Raw data reports - exporting the selected options in the same way as option questions
5. Combined reports - raw data report consisting of two data sets (2 sheets) with references to each other (design work needed) - in the following iterations 
### Links to documents

https://github.com/akvo/akvo-product-design/blob/master/FLOW/Features/110-LookupQuestions/FunctionalDesing.md

https://github.com/akvo/akvo-product-design/blob/c3b685ffd777b4156be9f287a8786a45d1452b7d/FLOW/Features/110-LookupQuestions/TechnicalDesign.md

**Comment by janagombitova** [comment]
### Design for app view: 

![look up question_ single_multi option](https://cloud.githubusercontent.com/assets/12456965/9301268/75c31c84-44cd-11e5-8d84-074a3dc285c5.png)

**Need to decide**
- Is it technically possible to provide a dropdown menu for lookup questions where only single select is enabled instead of a list to avoid too long lists in the app? 
- Is scrolling technically possible within the list of options when multiple select is enabled? If so, what is the min amount of options needed to enable scrolling?

**Comment by janagombitova** [comment]
### Design for dashboard on survey creation level

**Changes proposed**
- Question name - user will be able to customise the question name (as with all other question types). The 'preview' shows from which parts the list will be referenced from.

**Comment by ichinaski** [comment]
> Is it technically possible to provide a dropdown menu for lookup questions where only single select is enabled instead of a list to avoid too long lists in the app?

Yes, this is no problem.

> Is scrolling technically possible within the list of options when multiple select is enabled? If so, what is the min amount of options needed to enable scrolling?

It is (by default) automatically handled by the Android platform, depending on the screen size and number of items, etc. If the size is larger than the screen, scroll is automatically provided.

**Comment by mtwestra** [comment]
@iperdomo, @janagombitova my comments on the technical design:
1) on the dashboard - I think a user should select the survey, not the form.
2) app - I think a dropdown rendering should be one of the options - checkboxes could be another. This could be determined by a setting, perhaps. We need to think of a way multiple selections can be made.

**Comment by iperdomo** [comment]
@mtwestra 

> 1) on the dashboard - I think a user should select the survey, not the form.

If is a non monitoring survey, we need to pick the form that serves a _dataset_ ?

> 2) app - I think a dropdown rendering should be one of the options - checkboxes could be another. This could be determined by a setting, perhaps. We need to think of a way multiple selections can be made.

If we allow checkbox, we're stating that we allow _multiple_ answers, then the answer is not a single answer, but potentially, multiple ones? I think that for this first iteration we should support only a dropdown, and define how we want to _pack_ multiple answers.

cc/ @janagombitova @ichinaski

**Comment by iperdomo** [comment]
> If is a non monitoring survey, we need to pick the form that serves a dataset ?

I see that we don't support more than one form in non-monitoring surveys

**Comment by janagombitova** [comment]
#### Based on the technical design, these changes to the mockups apply: 
- form and question selection are not needed, as with the first iteration we will use the data point name to create the lookup list
- 'Add question' button also not needed for this iteration
- Preview will show the question (string of questions) which have 'Use as data point name' selected. 
   - Example: Student first name_Student second name_Age
- 'Option details' please change to 'Settings' - to maintain consistency within the dashboard

@Kiarii Could you please apply the changes to the design? Thank you.  

#### To be decided:
1. Will we support a multi select option for the list in the first iteration? 

2. How will the reports look like? 

   **Proposal:** 
  As we will use the data point name as the answer value, it will remain in the same format. To enable linking the answer to the original form, I suggest we add the data point ID as well. I think there are two ways how to deal with this, either we pack both answer with data point ID in one cell, or we create two columns, one holding the selected answer (data point name) and the other holding the source data point ID. 

   I personally prefer splitting them into two separate columns. 

![look up reports](https://cloud.githubusercontent.com/assets/12456965/9760689/ac0cabf2-56f7-11e5-84cd-9e3e781c0382.png)

@mtwestra @iperdomo @muloem @jonase @ichinaski What are your thoughts on this?

**Comment by Kiarii** [comment]
changes to mock up:
- removed: Add question, Form and question selection
- changed Options details to Settings
- added Survey selection

![look up question 5](https://cloud.githubusercontent.com/assets/12692444/9785496/77905bb6-57bb-11e5-8ada-aba28e5ff9a6.png)

**Comment by janagombitova** [comment]
After team week discussion on how we will approach this feature, we have decided to limit the first implementation in order to provide sufficient functionality and at the same time test how it works. The pieces that will not be implemented in the first iteration, will be added in the following ones.

The limitations are following: 
- no 'Allow multiple'
- no preview after defining the lookup question - 'data point name Preview' 

**To be decided:** How to generate lookup question answers in reports. See suggestions above.

**Comment by janagombitova** [comment]
Closing this issue for now, as the idea of Look up questions or the problems that it is to solve have not came up in any recent user research. Most cases are handled by either cascading questions (that are kept up to date) or monitoring
