### ISSUE TITLE
Expanding repeat question groups functionality

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-product-design#113]
DRAFT
### Overview

Currently repeatable question groups are working on the dashboard and the app in a first spam of functionality. The user determines the amount of repeats of a particular question group directly in the app while collecting data by pressing 'repeat group' button.

We want to expand the functionality of the repeatable question groups by creating:
- A way to fix the number of repetitions by letting it depend on the answer to a number question
  - Example: 
    Question: How many children do you have? Answer: 7 In the app the chosen question group will be repeated 7 times automatically
   - Example: 
   There are some occasions where a repeating group feature would make the most sense in a survey, but our field staff always have trouble filling these out correctly. So I'm requesting a feature that works like this:- Say the registration form is for a water committee. We are monitoring the water committee monthly. The water committee is responsible for multiple water points (this is how the situation works in Cambodia, for example). We want to know basic functionality details about each water point. Instead of a repeating group, I would like the option of saying there are 2 drilled wells, and then being asked questions about drilled well # 1 and then drilled well #2. Then saying there are 3 ponds, and being prompted to answer questions about pond #1, then pond #2, then pond #3. - We have this same issue with a school baseline form where we are trying to get detailed information about each latrine block. Because repeating groups are too complicated, we would like to be able to say how many latrine blocks there are and then being prompted to answer questions about each one.
- A way to let the number of repeats depend on an earlier option question
  - Example: Question: What is your favourite vegetable? Options: carrot, pepper, tomato, broccoli Answer: carrot and broccoli. In the app the chosen question group will be repeated twice, once for carrot and once for broccoli. In the view on the dashboard, the user will see that the particular repeats are linked to the chosen options 
- A way to let the number of repeats depend on a static list of items.

**Comment by muloem** [comment]
Perhaps part of the work on expansion of RQG is to fix the issue with enabling users to do data analysis on the exported reports?  At the moment it seems to be an issue that keeps coming  up that users are not able to do analysis because of the format.  I am not sure about the outcomes of your discussions with the different use cases but from support it appears that way.
@Geerts can also give some input

**Comment by Geerts** [comment]
I think a good improvement would be to duplicate instance number on every row of the repeated question (right now it's only on the first row). This way partners can use vlookups again to analyse monitoring surveys. 

I think this should be a separate ticket as it's really product improvement instead of feature expansion.

**Comment by Geerts** [comment]
For now we also have this workaround: https://akvoflow.supporthero.io/article/show/im-having-problems-analysing-monitoring-raw-data-reports-with-repeating-questions

**Comment by janagombitova** [comment]
Created via Reamaze:

Link: https://akvoo.reamaze.com/admin/conversations/akvoflow-support-request-number-65409-from-llange-at-lifewater-dot-org

**Comment by janagombitova** [comment]
We have made multiple improvements to how RQGs are handles in viewing and exporting data. We have not changed how they are filled in in the field, thus created an issue here: https://github.com/akvo/akvo-flow/issues/2940
