### ISSUE TITLE
Simplifying the FLOW app 

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-product-design#114]
### Overview

At the moment, the FLOW app appears in a single way, with the list of surveys at the home screen, from which you can select a survey, create a datapoint, etc. This covers the most generic workflow where people have multiple surveys, and a survey can support monitoring. However, we are starting to see use cases in which people want to download the app, have a minimum of configuration, and then have a very simple user interface which brings them more directly to the data collection process. At the moment, we can't cover this. 

The initial idea was to create a second configuration for the FLOW app, which then results in having two apps (the original one and the 'simpler' one). As this makes the user work flow even more complicated, we decided to redefine the app as it is and simplify the work flow. 

#### Initial changes:

1. Side bar menu, which holds the list of assigned Surveys, Settings, User management (with potentially more as Notifications, etc) 
2. Home screen shows the the last survey the user worked on with a list of data points. From here the user can directly by pressing '+' icon collect new data.  If she wants to collect data for another surveys, she needs to select via the side bar menu 
3. simplified action icon view in the top header - all icons as search, sort, stats, sync will be placed under one 'more' icon
4. '+' icon in the top header enabling the user to start a new data collection (to create a new data point)
5. each header will represent the main item the user is currently in (survey, folder, data point). For example,  if I open a data point on the app, then the header will not hold the 'survey name', but the 'data point name'. 
   - in the case of data points - header: data point name + sub-header: data point ID
   - in the case of forms, possibility to add the version as a sub-header as well
   - when creating a new data point the header will be: "New data point". Once the form is submitted, the data point name is derived from the answers submitted. 
6. additional changes (to be defined and added)

#### Simplification

- remove the 'survey selection' screen and add it to the side bar menu
- decreasing the amount of action icons in the top header 
   - second level actions (as search, sort, stats, sync) which the user does not primarily use as often as in comparison with filling in a new form, will be added under a one overlaping ' more' icon. 
   - users and settings will be added into the side bar menu
- less steps the user must take to start collecting data
- user remains logged in after leaving the app
- more to be added 

#### Limitations
- No customised branding

**Comment by mtwestra** [comment]
We need to discuss if customised branding is part of this

**Comment by ichinaski** [comment]
**Ideas and insights:**
* [Simpler configuration of app](https://docs.google.com/document/d/1h2poywxExCqJGp8Kk2Odc4vb9B-Ho-7qcTs8drfyREQ/edit#)
* [App workflow and UX (Iñigo)](https://docs.google.com/document/d/1Fqiy17fvccGOMcGBBk4sLIpZRWw8C6JKWW2IYIvby-g/edit)

**Design and mockups:**
* [Iñigo](https://www.dropbox.com/s/9vd6kqsij0mji3y/inigo_proposal.png?dl=0)
* [Kiarii](https://www.dropbox.com/s/p6qn3gzxhztwab1/simple%20app%20ux%20-%20kiariis%20proposal.png?dl=0)
* [Jana & Mark](https://www.dropbox.com/sh/rw0zefay85lpjar/AACGnaJIeC0U27nhjc72aUpNa?dl=0)

**Decisions:**
* We'll start by creating the side menu, which is part of all designs. A survey will always be selected by default (the most recent one). This will effectively remove one navigation step in all the use cases (monitored and non-monited surveys).

**Comment by janagombitova** [comment]
Latest mock ups: 
![simple app ux sketch 5-5](https://cloud.githubusercontent.com/assets/12456965/9275742/924c24d4-429f-11e5-94d9-324b72cd211c.png)

**Comment by janagombitova** [comment]
User testing document with feedback and insights: https://docs.google.com/document/d/1-UyUCfT9pOx7Vwuitgx7WKXCmieFhw29q1TINFr-6Kw/edit

**Comment by janagombitova** [comment]
New design of FLOW app - version 2.2.0 released with 1.9.2 dashboard on 5th November 2015.
