### ISSUE TITLE
Review Akvo RSR account registration process

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-product-design#122]
At this moment there are two issues with the registration process. 

- New RSR users need to register for an account and then connect themselves to an organisation. This process involves a lot of steps and the procedure is not clear to most people. 

- For Akvo staff there are several places in the admin and in MyRSR where they can or need to activate a new user registration and give them the appropriate rights. This is confusing and needs to be reviewed. 

This needs further thinking, but we need to take into account we will move towards a system in which we will offer partners the possibility to publish their projects in one of the following three tools: IATI / RSR  / RSR impact. This will also have consequences for the registration process. We need to think about the possibilities to automise this further.

**Comment by nadiagorchakova** [comment]
the issue is quite old and is not relevant any more.
