### ISSUE TITLE
Create standard report templates

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-product-design#127]
We need to define standard reports that can be exported from RSR. A first list:

- totals for financial data (RVO for example asked for this and would like to see this in graphs)
- overview of projects with: total number of updates, last update, last edited (in editor), project status, total budget, total expenditure, number of partners, planned period (planned end date - planned start date), actual period (actual end date - actual start date), 
- number of updates per time period (e.g. month for a set timeframe)
- progress on results data entry: per project the following: number of results, number of indicators, number of target values, number of actual values
- A user will want to see the above filtered for: a specific organisation or parent project + child projects or akvo page selection
- A link to the project page and to the project in editor mode helps the user to verify data further or edit the projects that need updates.

**Comment by lauraroverts** [comment]
- Overview of project updates within a certain timeframe, including text and photo

**Comment by mtwestra** [comment]
Data usage / quality reports / admin overview
* projects not touched last year
* incomplete projects (no photo)
* end date 3 months ago, and not finished
* most active users

**Comment by mtwestra** [comment]
Management informatie: Portfolio overview:
* Number of projects / per country / per region
* Budget - total / per country / per region
* Views per project (Piwik)
* Updates
* Sectoren

**Comment by mtwestra** [comment]
Timeline overview: 
* number of projects started / ended per year based on start/end date
* updates per month / year

**Comment by lauraroverts** [comment]
In progress
