### ISSUE TITLE
API Project and Organisation Upload via Admin

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-product-design#13]
This issue is an initial placeholder to talk about the feature of moving the API write functionality into the Admin.

More info to follow.

**Comment by adriancollier** [comment]
I think this feature is still very much relevant for us, and we should look at how we can built this along with IATI Export and automation of the IATI Import processes we have in place all together.

A mockup: https://github.com/akvo/akvo-product-design/blob/master/RSR/Features/13-ProjectOrgUpload/FunctionalDesign/ProjectOrgUpload.md

**Comment by lauraroverts** [comment]
@zzgvh is this issue still relevant? As far as I know it is already possible to add organisations/projects via the API.
