### ISSUE TITLE
Dealing with sensor data

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-product-design#136]
At the moment, we don't have a good solution for capturing sensor data. The main current use case is the water level and air quality sensors that have been created by SODAQ, and in addition to that the (huge) increase in internet-enabled sensors that is expected in the coming period, such as enabled by the LoRa technology. A proper product description for this still needs to be completed.

This topic falls under the 'internet of things', and a lot of infrastructure has been build around that recently, most of them commercial. Examples are  
- http://www.thingpark.com/en
- http://www.salesforce.com/iot-cloud/
- Google, Amazon, Microsoft are all building cloud based tools for this
- http://hortonworks.com/info/data-ingestion/
- A very interesting and well-supported tool for building data workflows is http://nodered.org/
- using the ELK stack, as we have already gained experience in Elastic Search and Kibana:
  http://www.paluch.biz/blog/134-capturing-and-visualizing-sensor-data-using-the-elk-stack.html. This article goes through setting up Logstash to receive sensor data, and then visualise it with Kibana.

As the shape and size of sensor data is very different from the type of data collected by FLOW, it seems to be the case that capturing sensor data through FLOW might not be the best fit.

Basic set of requirements:
- Ability to define a sensor as a data source, and to accept / read /store sensor data from different sources, such as an MQTT server, API call, or low-level through a TCP port. Basically - an Akvo endpoint accepting sensor input
- Ability to see the sensor data in its raw form, and to define data transformations such as filtering, thresholding, feature extraction, etc
- Ability to define charts and dashboards based on this data

The second and third requirements are clearly covered by DASH. However, for the first requirement this is not so clear, as until now we have said that DASH will be a way to visualise existing data, and treat it as read-only from some data source. So it is unclear where/how we should define a sensor, accept and store data from it. Once the data is in some datastore, it will be easy to connect to it from DASH and handle the second and third use case.

One option could be to create a producer for the unified log which captures sensor input and its it to the log, combined with a consumer which stores it in something like a postgresql datastore. One question is if this would be a good fit for large amounts of sensor data, which by its nature can be high-frequency.

Another option is to see how far nodered (http://nodered.org/) can take us in helping create a simple UI for wiring things up.

It would be very good if we can come up with a solution that requires only a minimum of additional UI / systems to be created, if at all.

Of course we'll go through the proper cycle of user stories etc, but I wanted to get a round of first comments. So @iperdomo, @jonase, opinions?

**Comment by iperdomo** [comment]
> One question is if this would be a good fit for large amounts of sensor data, which by its nature can be high-frequency.

Do we have numbers for this? Ops/sec that we need to support?

> Another option is to see how far nodered (http://nodered.org/) can take us in helping create a simple UI for wiring things up.

This is a node based software and I guess we try to minimize the technology stacks we maintain?

Other open source projects we should check:

* http://www.kaaproject.org/
* http://iot.eclipse.org/projects

**Comment by mtwestra** [comment]
On numbers:
* A typical sensor could generate about 1 data point per minute, at worst case. This is about 1500 datapoints per day for a single sensor.
* say we aim first to support 5000 sensors. That would be 7.5M datapoints per day, or about 90 writes per second.

Some additional info:
* "Node-red has hundreds of plugins for all sorts of hardware"
* "Kaa project was indeed started not with the intention to replicate the Node-red functionality. Numerous 3-rd party integrations were done using Kaa - but its primary focus is on enabling the OEM / vendors’ “cloud” / back-end systems in a reliable, scalable, and maintainable fashion."

**Comment by janagombitova** [comment]
Closing this issue for now. We are not working with sensor data at the moment and external datasets can be imported to be used. It is an interesting idea but we need to see if sensors as a data source fit our product strategy, our target audience and market and if we will pursue this idea in the future we can reopen the issue in the right repo
