### ISSUE TITLE
Investigate fingerprinting biometrics

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-product-design#137]
We should investigate fingerprint capture technology and see if it worth while coupling this to FLOW. Fingerprints have a large number of applications in the development sector including:
- health / hospitals
- vaccinations
- distribution of aid
- microfinance

An interesting product is http://www.simprints.com/, developed by a not-for-profit organisation. This is being developed in the course of 2016.

**Comment by janagombitova** [comment]
Interesting idea that is worth looking into. When evaluating its value, feasibility and usability we need to also consider legal and security repercussions of storing person data of this kind.
