### ISSUE TITLE
What information is useful to show in survey overview? 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-product-design#180]
**To be investigated and more information to be added**
### Publishing Status 
Make publishing status easily determined from the survey overview https://github.com/akvo/akvo-flow/issues/1047

[rumca commented on Dec 18, 2014]

This ones not an issue, but it would perhaps be nice to include publishing status along with "created", "modified", "type", and "language" on the survey overview:

![screen shot 2014-12-10 at 12 03 07](https://cloud.githubusercontent.com/assets/3003031/5375656/88b8fbde-8064-11e4-8cca-8eeba525207e.png)

Secondly, we may consider also showing the form versions. 

Thirdly, publishing date: 
Would like to: have a ‘Publish date’ positioned next to the creation and modification date.
 
So that: if different people are working in the same survey, it is clear to everyone when the publication of the survey occurred. This would help users a) when multiple people are editing at the same time, and b) for clearer co-ordination when distributing the updated forms to the field.
Currently the time of a survey form publishing is recorded in messages tab. However, this expires within a set number of messages. Later if a users is wanting to check when it was last published, they do not have a set time or date.

### Number of forms and questions in the surveys 

Currently the user cannot see if the survey is a monitoring one or not, or how big the surveys is. It would be useful if she can get that information without having to open up the survey. A problem can arise with the counting (as it is a problem already)

---- 
- Created date, Modified date, Published date + user 
- forms count

**Comment by loicsans** [comment]
One other useful addition would be to display the number of surveys inside each folders. @muloem is that possible to pull this metadata?

**Comment by janagombitova** [comment]
I am going to close off this issue for now as we are redesigning the UX with Grouping things app. But lets keep these concerns in mind in the work there
