### ISSUE TITLE
Lumen user admin

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-product-design#191]
### Lumen user admin

This issue will hold the discussion around user management for Lumen.
#### Key Concepts
- User - a person with a Lumen login account
- Group - a collection of users that share the same roles. A user must be a member of at least one user group.
- Role - a role which is given to a group, containing the set of permissions
- Permission - the permission to take a certain action
- Resource - describes a resource, such as a collection.

There are a number of things to consider in structuring the user admin. Mainly, it is about deciding how access rights and permissions are organised - on the individual user level or on the user group level - and from where.

In FLOW, this is done as follows:
1) custom roles can be defined as custom sets of permissions
2) each user is given a set of (roles,resource) combinations, that define both access rights to a resource and permisions on that resource.

The drawback of this system is that with a large number of users this becomes hard to manage, because there are no user groups.

An alternative system that uses the same concepts but organises them a bit differently would be:
1) Users are members of user groups.
2) Two groups are default: all users and administrators
2) a user group or a user can be assigned a role on some resource
3) a role can be customised as a set of permissions

This allows people to manage roles and permissions in two ways:
- for small teams, the whole team might have access to the whole workspace with all resources (collections)
- for larger teams, an administrator could either assign individual users to different resources, or create user groups which have access to resources, and place users in those groups.
#### Phasing

It would be good if we can phase the introduction of user management, for example in the following way:

step 1) Ability to create and manage users and user groups, with all users having access to all resources

step 2) Ability to assign access rights and roles to a user group and individual users to specific resources / collections, with the roles predefined.

step 3) Ability to create custom roles where the permissions can be customised.
##### Admin area
- As an admin user, I want to have access to a space where I can administrate users
##### Overview / Dashboard
- As an admin user, when I go to the admin area, I'd like to get an overview of the users in the system:

1) Total number of users
2) pending invitations
3) number of user groups.

From this overview, I'd also like to have simple links to common activities, such as inviting a new user, sending a reminder to an invited user, and creating a new group.
##### Users
- When I go the user management section, I would like to see a table of active users, with name, email address, role/resources, and groups the user is part of.
- I'd like to be able to see the pending invitations, and to send out new invitations
- When I invite a new member, I'd like to be able to select which groups this user will be part of.
- I'd like an easy way to select different groups as a filter, so I can see only the membership of people to that specific group.
- I'd like to have the ability to add a resource/role combination to a user
##### User Groups
- I'd like to be able to have a page where I can see all user groups, and where I can define new user groups
- When I click on a user group, I would like to see the users in that group, and have the ability to remove or add users.
- I'd like to have the ability to add a resource/role combination to a user group
##### Roles
- I'd like to have a page where I can see all the roles defined
- I'd like to be able to select which permissions the role consists of, and to create new roles

**Comment by iperdomo** [comment]
If we're going to _outsource_ the internals of the authorization process to Keycloak, it would be good to understand their core concepts,  and align them with ours.

* https://keycloak.gitbooks.io/authorization-services-guide/content/v/2.2/topics/overview/overview.html
* https://keycloak.gitbooks.io/authorization-services-guide/content/v/2.2/topics/overview/terminology.html

**Comment by mtwestra** [comment]
After reviewing the current Keycloak functionality, these are the findings:

1) Keycloak has introduced Authorization services that offer fine-grained authorization of resources, using attribute, role, user or rule based access rules.

2) Currently, there is not really a good way to access these functionalities through the REST API, however, there is a Java API that can be used to access the functionality.

3) The terminology for the Authorization is:

* resources - a resource to be protected, characterised by a name, an URI, and a type
* scopes - a type of action that can be applied to the resource, such as view, delete, etc. Characterised by a name
* policies - a statement about allowing or disallowing based on rules. Rules can be user based, scope based or resource based.

Keycloak makes a difference between the terms 'policies' and 'permissions', but under the hood both are policies.

4) Policy enforcement can be done on the basis of the URI of the resource, including use of wildcards

**Comment by mtwestra** [comment]
As an initial phase, we can start with the simplest system: to create users that have access to everything inside a Lumen workspace. From there, we can start to introduced other concepts such as team spaces and folders that are authorization-enabled.

That would mean to just retain the users tab in this visual design: https://drive.google.com/drive/folders/0BwEEfk7lVujkUXlMb1ltTEdqWEE
