### ISSUE TITLE
Derived column implementation

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-product-design#192]
This issue will hold the discussion about how to implement derived columns.
#### User stories

The original user stories are reproduced here:
I have a dataset in which I have the amount of crops sold for 10 different crops, for individual farmers. However, I am interested in the total amount the farmer has sold. So I want to create a new column, ‘total sold’, which is the numerical sum of all the 10 columns holding the individual amounts.

I have a dataset about food security, based on the HFIAS survey set. In the end, I want to create a simple ‘traffic sign’ visualisation, where ‘green’ means no problem, ‘orange’ means sometimes food insecure, and ‘red’ means food insecure. For this, I want to combine the answers to a number of questions to a single ‘score’. For example, if the number of days people were hungry in the last 3 months is zero, AND people were not worried about food, AND their neighbours also weren’t hungry, THEN the score is 0, meaning green. So I want a way to create a formula which combines the values in different columns, and creates a new value in a new column.

I have a live dataset of mothers, and I want to make an internal dashboard so I can see which mothers are due for delivery. For this, I need a column with the expected delivery date. However, in the original data, the only thing we have is the date of the last menstruation. So I want to make a new column called ‘expected delivery’, which adds 9 months to the date of last menstruation.

I have a dataset on compliance of farmer compliance to a certification questionnaire. I want to combine the columns in various ways. For example, I want to add up all the yes/no answers for a number of questions to a total score, and compute the percentage of compliance. For example, if from 20 questions the farmer has answered "yes" on 15, I want to get the result of 75%. In other cases, I want to count a score only if it exceeds a certain treshold.

Overall user story - As a user I would like to create a new column by using ‘formula’ on a number of specific columns in order to derive ‘higher value’ data based on existing columns. This needs to allow the user to ‘score / grade’ a datapoint - using a complex equation on existing data.
#### Approach

After internal discussion, we agreed that we will use javascript as our main expression language. We need to think of solutions for the following questions:
- how to restrict the javascript to a set of save functions
- how to check validity of the javascript and communicate problems to the user
- how to refer to columns
#### Types of functions to support

https://github.com/vega/vega/wiki/Expressions has a good list of expressions
- mathematical functions including aggregation functions
- date / time functions
- constants (pi, e, ...)
- sequence functions
- string functions
- regular expression
- control flow (if)

An alternative to look at could be General Refine Expression Language: https://github.com/OpenRefine/OpenRefine/wiki/General-Refine-Expression-Language
#### Inspiration / Ideas
- Vega uses a similar approach in the way it implements formulas in data transforms (https://github.com/vega/vega/wiki/Data-Transforms#-formula). It uses an expression language (https://github.com/vega/vega/wiki/Expressions) which is a subset of javascript. It includes an expression parser and code generator (https://github.com/vega/vega-expression).
- The vega parser is based on a different project: Esprima (http://esprima.org/), which also parses javascript code and can return executable code, which can be run by Nashorn
- An alternative could be the General Refine Expression Language, explained here: https://github.com/OpenRefine/OpenRefine/wiki/General-Refine-Expression-Language. This is written in Java, so could be executed directly from a clojure backend.

**Comment by iperdomo** [comment]
> * how to restrict the javascript to a set of save functions

With Nashorn. You can disable _all_ Java interop.

https://github.com/shekhargulati/java8-the-missing-tutorial/blob/master/10-nashorn.md#turning-off-java-language-access


> * how to check validity of the javascript and communicate problems to the user

I checked Esprima (http://esprima.org/) and Tern (http://ternjs.net/) but also web based editors support JavaScript and report nice user messages to give feedback as early as possible (e.g. Autocompletion, linting, etc)

- https://ace.c9.io/
- http://codemirror.net/

> * how to refer to columns

https://github.com/OpenRefine/OpenRefine/wiki/Variables#variables

**Comment by jonase** [comment]
We also need to make sure that the result type (`number/date/text/...`) is correct. Without static typing the user might have to specify the desired result type which we can enforce and use an `onError` strategy if the user defined function return type is invalid.

**Comment by jonase** [comment]
I think we also need to be able to timeout javascript functions to guard against things like `while(true) {}`. Perhaps we can use esprima to inject `if (java.lang.Thread.interrupted()) break;` at the beginning of each loop construct and function body? That way we can call `thread.cancel(true)` from the Clojure code. 

Another possibility is to disallow looping constructs and recursion which I think can be achieved by walking the esprima AST  (I'm not 100% sure if that guarantees termination).

**Comment by mtwestra** [comment]
@jonase, the subset that vega uses doesn't allow control structures beyond IF, as far as I can tell. (https://github.com/vega/vega/wiki/Expressions)

**Comment by mtwestra** [comment]
We need to decide how we phase the introduction of this, and what the user interface will look like. Some inspiration:
* Excel Formulas
* Access Expression builder (https://support.office.com/en-us/article/Use-the-Expression-Builder-56214db9-8b54-44f3-bc19-2a55427b5d4c)

**Comment by jonase** [comment]
There's an initial [ADR](https://github.com/akvo/akvo-lumen/blob/develop/doc/arch/adr-005-transforms-in-js.md) written

**Comment by jonase** [comment]
Detailed research document can be found at https://github.com/akvo/akvo-lumen/issues/428#issuecomment-261237765
