### ISSUE TITLE
Improve Lumen transforms

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-product-design#196]
A generic issue to capture discussions on Lumen transforms
- [x]  geocoding
- [ ]  Cluster and bulk edits
- [ ]  unique values and bulk edits
- [x]  split column
- [ ]  group and aggregate
- [ ]  deduplicate
- [ ]  removing rows
- [x]  join data sets

**Comment by janagombitova** [comment]
Some of the ideas are already in place the others are moved to the Lumen repo and their implementation will depend on the needs users have around data cleaning
