### ISSUE TITLE
Lumen curated data sets

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-product-design#199]
Issue to hold work on integrating curated data sets in Lumen

**Comment by nadiagorchakova** [comment]
Suggestions on data sources for curated datasets by Mark and Henry:
(It also went into Hilton Foundation grant progress report)

•	IEA - International Energy Agency atlas
•	World Bank - The World Bank’s World Development Indicators (http://data.worldbank.org/data-catalog/world-development-indicators)
•	IMF - International Monetary Fund data site (https://www.imf.org/en/Data)
•	GAUL - Global Administrative Unit Layers - GIS administrative boundaries (http://www.fao.org/geonetwork/srv/en/metadata.show?id=12691)
•	GADM - World administrative boundaries (www.gadm.org)
•	UNDP - UNDP’s Human Development Index (HDI) (http://hdr.undp.org/en/data)
•	Population density - Gridded Population of the World (http://beta.sedac.ciesin.columbia.edu/data/collection/gpw-v4)
•	Gapminder data (http://www.gapminder.org/data/)

**Comment by nadiagorchakova** [comment]
One more suggested source for curated datasets (discovered it recently)

- [Data.world](https://data.world/) API documentation: https://docs.data.world/documentation/api/

**Comment by janagombitova** [comment]
Have added the dataset sources to a support article and we will consider this opportunity when discussing also survey template libraries under the new strategy of a connect Flow + Lumen product
