### ISSUE TITLE
Data cleaning

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-product-design#2]
Data cleaning refers to the proces of editing survey data after it has been collected, usually in bulk. Common data cleaning processes include correcting grammar, punctuation, capitalization and spelling, normalizing similar responses such as "don't know" and "I don't know", finding explicit errors such as wrong dates, and adding additional information such as water quality results.

In the FLOW 1.5 system, data cleaning can be done by exporting the data of a particular survey to an Excel file, and use Excel functionality such as filters, sorting, and search-and-replace to do the data cleaning. After the cleaning, the Excel file is uploaded to the FLOW system again. However, this process carries the very real risk of data corruption, as Excel does not force keeping rows of data together, making it possible to sort one column without sorting the others. 

For Akvo FLOW, we will create data cleaning tools that are part of the Dashboard, and that ensure data integrity by constraining the cleaning operations. In addition, we will add an audit system, which will log all changes made to data, recording the previous value, the user that made the change, and the time the change was made.

In a first implementation, we will introduce:
- fast display of restricted number of columns
- display unique values in a column
- search-and-replace in a column
- filter a column
- capture change audit information 
- edit individual cells

**Functional design document**
https://github.com/akvo/akvo-product-design/blob/master/FLOW/Features/2-DataCleaning/FunctionalDesign/DataCleaning.md

**Comment by mtwestra** [comment]
Needs to include a full and transparent audit trail of data changes.

**Comment by janagombitova** [comment]
Note from issue: https://github.com/akvo/akvo-flow/issues/419

[mtwestra commented on Oct 31, 2013]
Current behaviour:

data cleaning can be done per record
data cleaning can be done by exporting a raw data report, cleaning data, and importing again.
The excel-route of data cleaning is powerful, but also fragile: it is easy to mess up data and upload it again. Therefore, we would like to add better data cleaning features to the dashboard.

In consultation with Keri of Water for people, this is a first list of desired functionality:
1) Grammar, Punctuation, Capitalization and Spelling 
2) Normalizing similar responses (for example making "don't know" "do not know" and "I don't know" all into "don't know") 
3) Finding Explicit Errors (for example: finding dates that are clearly wrong like 1798 and fixing those or eliminating them if the real answer is unknowable). 
4) Adding in additional information after a data collection (for example: if we do water quality testing as part of the survey we don't get results from the tests for several days so in practice surveys are submitted without the results and they are hand entered into the spreadsheet later as part of the data cleaning process.

**Comment by janagombitova** [comment]
Lumen handles some of the most commonly used data cleaning needs and Flow allows to clean offline. There are many overlaps and well as issues in the current implementation we have in place causing confusion among our users. We will first connect the two products, then ensure Lumen transformations are reflected on the Flow database and then see how we need to further improve data cleaning in its respective repository. For now closing this issue
