### ISSUE TITLE
CartoDB integration

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-product-design#21]
### Overview

Maps are an important way people interact with data. It helps judge progress of data collection, the spatial spread of data, and sometimes clear spatial patterns emerge. To enable users explore data using maps, they need some flexibility in what is displayed. This feature will make it possible to: 1) use street, satellite and terrain backgrounds, 2) show clustered data on different zoom levels, 3) enable filtering of data by survey, 4) styling markers (color, symbol) based on survey, and 3) display detailed data for individual points.

Because mapping is hard, we have decided to integrate flow with the open source CartoDB tool. We have made a carefull investigation of all the options, which clearly led to CartoDB as the most appropriate solution.
### Initial features

In the first phase, we will introduce:
- Use mapbox as tile provider for street, satellite and terrain tiles
- display data of individual surveys on map using standard markers
- enable users to specify popup style and content

Phase 2 will introduce:
- enable data-driven styling of markers and custom icons
- awareness of administrative boundaries
- enable filtering of datasets
- enable creation and saving of visualisations
- handle translations of questions
### Documents

Functional design document: https://github.com/akvo/akvo-product-design/blob/master/FLOW/Features/21-MapDisplay/FunctionalDesign/MapDisplay.md

Technical design document: https://github.com/akvo/akvo-product-design/blob/master/FLOW/Features/21-MapDisplay/TechnicalDesign/MapDisplay.md

Wiki: https://github.com/akvo/akvo-product-design/wiki/CartoDB-integration

**Comment by janagombitova** [comment]
Based on feedback and ideas from Kiarii, here are minor implementation UI + UX fixes for the map, which we can add in with the integration: 

![cartodb integration](https://cloud.githubusercontent.com/assets/12456965/9003436/4ecf9f4c-376e-11e5-8624-56dbdc13743e.png)

Disable scrolling on the overall map page. Enable scrolling only in the sidebar

**Comment by janagombitova** [comment]
After the initial test implementation we will follow with the 2nd milestone: 
https://github.com/akvo/akvo-flow/issues/1389

**Comment by janagombitova** [comment]
We have decided to solely focus this issue on enabling Carto/Windshaft maps on Flow instances as part of this issue. The custom maps implementation is handled under a different issue.

**Comment by janagombitova** [comment]
The Windshaft implementation (currently in progress) will bring to the users: 
- no data point clusters on the map, each point will show separately 
- user will have to select the folder, survey form first before data points will show on the map 
- user can only select those forms she has access to 
- this map implementation will be done for both the public and private maps for each Flow instance 

After a new submission it will take 15 minutes for the unified log to "catch up" to log in the submission, so new data points will not appear on the map in real time, but after a 15 minutes delay. 

Further improvements to Flow maps can be found here: https://github.com/akvo/akvo-product-design/issues/274

**Comment by janagombitova** [comment]
Completed
