### ISSUE TITLE
Stylesheet refactoring on Flow dashboard

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-product-design#225]
The goal of this project is to create a more consistent and clean dashboard for our users. Over the course of time the design of the dashboard has become very inconsistent and cluttered. With this project we want to take small steps to improve the current status. See comment below on the sub-tasks.

**Comment by loicsans** [comment]
A summary of that work is inclosed here:

1. - Improve high level typography for readability and responsiveness
2. - Declutter and Remove all unnecessary iconography and most importantly not universally recognised visual representation of actions.
3. - Modal dialogs consistency across dashboard:  Identify when it’s necessary Use clear questions and options.
4. - Button: use sparingly and consistently. Same visual button across dashboard
5. - Grid / Layout: fix general problems of misalignment and spacing as well as responsiveness to different devices.  Investigate if using an existing css based framework would be beneficial.
6. - Form redesign meeting new standards for better user experience (floating labels, bigger fields and fonts, better grouping, better user feedbacks and error management)
7. - Investigate if we can add better contextual metadata info on folders and survey for best search-ability and find-ability.
8. - Find and Remove duplicated elements across dashboard (ie. Titles…)
9. - Pagination consistency
10. - Table improvement including sorting of columns and responsiveness.

**Comment by janagombitova** [comment]
@loicsans I have added some more items to the list and linked to issues in Flow repository. I find the last two items: form redesign and survey metadata quite large tasks that we can break down into smaller ones and start with low hanging fruit.

**Comment by janagombitova** [comment]
We should also add here the task to 
* [ ] simplify the colour palette on each page

There are many parts of the dashboard where we use multiple shades of a colour or even multiple different colours. We should decrease that to create a more elegant look. When looking at colours we not only need to consider background colours but also font and button colours. Small issues will be created to cover these changes

**Comment by janagombitova** [comment]
Separate issues created in the repos.
