### ISSUE TITLE
Linking RSR to the unified log

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-product-design#235]
According to our contractual obligations in PPP agreement, the following was promised:

"RSR will be linked to the unified log (a database that will share both RSR and FLOW data) so that integration between our products as well as CartoDB will be possible."

From the list of contractual obligations: https://docs.google.com/spreadsheets/d/1Dt5yhBlr_QydrJNVdSuiJrpurU6OH2jm4qpb50wCWrI/edit#gid=0

**Comment by nadiagorchakova** [comment]
Hi @iperdomo, has any research/initial thinking been done on this already?

**Comment by nadiagorchakova** [comment]
Talked with Ivan and Lars about it. The conclusion is that we should use [Bounded context](https://www.martinfowler.com/bliki/BoundedContext.html) approach to product integration and stay away from unified log. I will communicate to the partner team regarding our contractual obligations, that we chose in favour of a different integration strategy.

**Comment by iperdomo** [comment]
Hi, just to be clear, there is no _either-or_ here, we can just start publishing change events that will be useful (for RSR context), e.g. Maps. IMHO, given the current priority, the work needs to be _parked_, but doesn't mean that is not important and/or beneficial in the long run.
