### ISSUE TITLE
Derived column user interface

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-product-design#239]
This is a follow-up issue from #192 

The derived column functionality in Lumen has been implemented now and is functioning. The main elements of the functionality are:
* a user can create a derived column
* a user can enter a javascript expression (only expressions are allowed)
* when the expression can be parsed, the user can click 'derive' and the a new column is created.

The next step is to add more user interface elements to this core functionality, such as:
* assist the user when typing the expression with real-time syntax error feedback
* assist the user by making it easy to add a column reference, without having to type the name
* assist the user by adding help texts as part of the interface on which functions are possible, and how to build an expression
* in an existing derived column, make it possible to see the expression that was used to derive it
* allow the user to edit the expression of an existing derived column
* give the user a live preview the result of the current expression (if valid) on the first ten columns of the data

The relevance, completeness and priority of these items should be discussed during a story mapping session.

The above items can be divided in functionality *during* the building of an expression, and functionality on an *existing* derived column. For the latter, there is a technical issue that it can be possible other transforms could have been created after the initial derived column creation, which could be effected when the expression is edited. For example: I could create a derived column that creates some number, and then a next derived column could take that number as one of its inputs for a new expression. These 'chained' derived columns need to be handled correctly. 

The question therefore is that if an expression is edited, how this should be handled. Should it 'rewrite history' of the transformation log? Or should it check wether other transforms depend on it, and only allow the edit when there are no side effects for other transforms?

**Comment by janagombitova** [comment]
This issue will be handled progressively in the Lumen repository
