### ISSUE TITLE
Embedding Lumen content

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-product-design#253]
Our interns Melik and Magnus (Stockholm) researched embedding lumen data to websites using <iframe> tags, which should be supported by most web viewers (browsers).

<iframe width="800" height="400" scrolling="no" frameborder="0"  src="https://demo.akvolumen.org/s/SgTNnu07jMQ"></iframe> (graph)
<iframe width="1024" height="1075" scrolling="no" frameborder="0" src="https://demo.akvolumen.org/s/wV_TVxJxwQ8"></iframe> (dashboard)

The reason the first <iframe> (graph) has the specified dimensions is because the graph itself uses those width/height values, specified by the HTML <div class="Chart bar large" style="width: 800px; height: 400px;”> in the first demo.

The second <iframe> (Dashboard) has a width of 1024 pixels because when you try to decrease the width a Dashboard that contains a graph with a lot of submitters (first diagram for instance), the graph breaks (https://puu.sh/uwzrO/a2835d440e.png) and not all data can be seen. Some, if not most graphs can be resized and still retain integrity but in the case of the Dashboard diagram they recommend to not change the size values at all.

And here're different UI solutions:

<img width="925" alt="screen shot 2017-03-07 at 16 14 44" src="https://cloud.githubusercontent.com/assets/21127166/23662883/390e1408-0351-11e7-923d-55bf449416ef.png">

![image005](https://cloud.githubusercontent.com/assets/21127166/23662830/0a1b8e96-0351-11e7-8b01-02baffe3662e.jpg)

![image006](https://cloud.githubusercontent.com/assets/21127166/23662848/190d3cc4-0351-11e7-95dd-d12a2cbf3a8e.jpg)

**Comment by janagombitova** [comment]
Embedding was implemented for visualisations and dashboards.
