### ISSUE TITLE
Scoring feature in Lumen

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-product-design#255]
During our user story mapping session on scoring with Lumen dev team and @Kiarii, we came up with the following provisional workflow that still needs to be verified and refined:

<img width="1021" alt="screen shot 2017-03-27 at 18 25 34" src="https://cloud.githubusercontent.com/assets/21127166/24366876/d13ac946-131a-11e7-8c49-e54aec3054c6.png">

The full story mapping board with definitions, user problems and a provisional solution can be found here: https://app.mural.ly/invitation/mural/akvo8194/1488544015508?sender=loic4416&key=557173498

**Comment by janagombitova** [comment]
Lives in Lumen repo now
