### ISSUE TITLE
Consider showing captured location on map in Flow app

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-product-design#256]
# Context 
Currently when Alphonso captures location he can either type the coordinates manually or get the location info from the device. What he then sees are the numerical coordinates and the accuracy of the measurement (if captured from the device GPS). He does not have to go to a separate page on the phone to capture the location info, he simply does this in the form screen.

![screenshot_2017-03-27-11-57-38](https://cloud.githubusercontent.com/assets/12456965/24351383/c57d06e4-12e5-11e7-80eb-d9c448571e21.png)

# Opportunity
Alphonso has no real clue about the location captured as seeing coordinates does not tell him where  the location is, if it is where he wants it to be. To show the location on a map, besides the numerical value, can give him more insight on the coordinates he has captured.

Secondly, when capturing location manually he sometimes does not know the coordinates, so being able to add the point on a map and then get the coordinates can visually help him make sure he answered the question correctly.

We need to keep in mind a few cases though: 
- Alphonso usually collects data offline, thus he is not able to load in the map 
- the survey is set up by Salim who decides, if Alphonso can collect the location data only manually, only using the device's GPS or he can give Alphonso both options 
- when the location is being captured by the device, it takes a minutes (then times out) so Alphonso needs to see that the location is being captured and he should not be able to type in the values, as they will be overwritten 
- minimise the steps he needs to take when capturing the location data, seeing it on a map can be considered as an extra possible option for validation

**Comment by valllllll2000** [comment]
Update: the UI has been improved and while the location is being captured automatically, we display a loading dialog and the user cannot entrer manually unless he cancels manual input.
![screen shot 2017-04-04 at 13 59 24](https://cloud.githubusercontent.com/assets/12456965/24655569/08c72240-193f-11e7-8ffc-d49511989aff.png)

**Comment by janagombitova** [comment]
Moved here: https://github.com/akvo/akvo-flow-mobile/issues/1284
