### ISSUE TITLE
Merging datasets

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-product-design#260]
When working with data coming from different sources, it's necessary to join several datasets into one.

The easiest case is when the two tables have a **one-to-one relationship**. For instance:

<img width="558" alt="screen shot 2017-04-21 at 15 56 45" src="https://cloud.githubusercontent.com/assets/21127166/25280694/2b6da62e-26ab-11e7-8a2f-44543342716b.png">

(The country column which is common for both datasets is present only once in each dataset.)

The more difficult case is when two tables have **one-to-many relationship**. This will be a common case when merging Flow Registration with Flow Monitoring forms.  For instance:

<img width="546" alt="screen shot 2017-04-21 at 15 59 45" src="https://cloud.githubusercontent.com/assets/21127166/25280819/9241b214-26ab-11e7-9a3e-4204b205496c.png">

**A few examples how other tools handle one-to-many relationship in merged datasets:**

_1. Do an aggregation (sum, average, etc)._
This would result in the following merged dataset:

<img width="338" alt="screen shot 2017-04-21 at 16 06 28" src="https://cloud.githubusercontent.com/assets/21127166/25281074/80bc3ac2-26ac-11e7-9bdc-ccc75bbb51b5.png">

Downside of this method is that you cannot present and analyse trends over time as in time-series.

2. _Create repetition inside the merged table_

<img width="399" alt="screen shot 2017-04-21 at 16 20 16" src="https://cloud.githubusercontent.com/assets/21127166/25281709/748f5e76-26ae-11e7-972e-2f1926253dfe.png">

**The common merge steps that several other tools seem to use:**

- select the tables that should be merged
- select the merge column or 'source of match' (for instance, an Identifier or country, or both.. some tools have an option to merge on several matching columns)
- merge

Merging would normally result in a new dataset (no overwriting of the merged datasets themselves)

I think we need to hold a workshop to understand the issue better together.

**Comment by nadiagorchakova** [comment]
Talked with Karolina about the usual practice of merging datasets. She suggested we could take a similar approach to the JOIN function in SQL:

<img width="712" alt="screen shot 2017-06-09 at 16 28 07" src="https://user-images.githubusercontent.com/21127166/26980026-259bab68-4d31-11e7-9fbf-d1512ab55237.png">

Source: http://www.dofactory.com/sql/join

**Comment by janagombitova** [comment]
Implemented.
