### ISSUE TITLE
Multi-series line & area chart

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-product-design#261]
Multi-series line charts are most often used to compare how two or more variables change over time.
It's a graph that is commonly used in time-series analysis.

A multi-series line chart would look something like that:

<img width="540" alt="screen shot 2017-04-21 at 17 48 51" src="https://cloud.githubusercontent.com/assets/21127166/25285533/d5ce3a3e-26ba-11e7-9634-168047c28b52.png">

And here's an example of multi-series area chart:

<img width="482" alt="screen shot 2017-04-21 at 18 05 48" src="https://cloud.githubusercontent.com/assets/21127166/25286265/76558870-26bd-11e7-95b3-9bdf6dfcfddc.png">

In Lumen, we already have Line charts and Area charts, but so far, they only support single series. 

As to use cases, Flow monitoring data, for instance, could be best visualised using multi-series and area charts.

**Comment by janagombitova** [comment]
Issue recreated in Lumen's repo: https://github.com/akvo/akvo-lumen/issues/1886
