### ISSUE TITLE
Display authors of visualisations and dashboards

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-product-design#262]
In the long run, we'd like to make Lumen more collaborative. 
This might involve teams co-creating one dashboard. For this reason, it could be handy to see who created a visualisation or set up a dashboard, so that if you have any comments you can get in touch with this person.

It might also be helpful to see who updated the visualisation or dashboard last.

According to Jonas, this info sits in the database already, so it would be nice to make use of it.

**Comment by janagombitova** [comment]
Authors of visualisations and dashboards are shown in the library as well as creation time, also for datasets. Closing this issue for now
