### ISSUE TITLE
Messages in Flow - How can we improve them? 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-product-design#263]
The Messages tab holds a lot of information on background tasks that Flow performs. With some tasks (as data cleaning) we tell users to check the success of the actions first in the Messages tab, before proceeding. With some actions, the updates happen "invisibly", without the user knowing. 

Many users, especially those who keep track of the overall usage of their instance, look at the Messages tab to see what is going on. 

We should consider how to improve this page and its use, to be more clear. Here are some initial points, there for sure will be more once we dive deep: 
- Why do we have this tab? Is it a log of all events happening of the dashboard? 
- What information should we show here? 
- Should the user be able to click through also older messages than only the last one showing on the page? Should he be able to search or filter for something particular?
- Can the actions, where the user must now got to messages to see completion, be shown differently - avoiding this task? (like publishing a form, copying a survey, etc)
- What we show now, is it understandable? 
- What we show now, is it consistent? 
   - we show the folder/survey/form path differently based on the message type 
   - with some data cleaning actions we show the it was a success even if it wasn't

Lets start by knowing what we show currently and why and then we can talk on what value we can bring to this part of Flow

**Comment by janagombitova** [comment]
# Survey column

Another issue with the Messages is that they are inconsistent. For example, in the Survey column we sometimes only show the form name and sometimes the entire folder>survey>form path. Here are the rules up till now: 
- when copying a survey - show only form; 
- when publishing a form - show survey + form
- when data is synced - show folder + survey + form
- importing clean data unsuccessfully - show nothing 
- importing clean data successfully - show folder + survey + form

<img width="1197" alt="screen shot 2017-06-27 at 08 15 43" src="https://user-images.githubusercontent.com/12456965/27573246-384d0840-5b11-11e7-89c8-3e8922e73831.png">

<img width="1190" alt="screen shot 2017-06-27 at 09 21 00" src="https://user-images.githubusercontent.com/12456965/27575519-69774742-5b1a-11e7-957a-7cbeb47a815a.png">

<img width="1195" alt="screen shot 2017-06-27 at 09 39 35" src="https://user-images.githubusercontent.com/12456965/27576300-d7758f5e-5b1c-11e7-8183-f360e58340ff.png">

**Comment by stellanl** [comment]
And the path is severely broken - it is not updated when objects are copied or moved. It should not be displayed anywhere...

**Comment by stellanl** [comment]
Exports should also show up here. The emails we send after an export is a major security problem.

**Comment by janagombitova** [comment]
Duplicated here: https://github.com/akvo/akvo-product-design/issues/285
