### ISSUE TITLE
Integration with Akvo sites

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-product-design#264]
Lars Heemskerk suggested that **in the long term**, it would be helpful to publish Lumen visualisations directly into Akvo sites. Currently Akvo sites are using word press plugins and Carto maps to visualise partners' project data. Word press plugins are not powerful enough and Carto is too difficult to learn for some parters, so Lumen visualisations and maps could be a nice alternative there.
It's also in line with Akvo's long-term strategy to create integrations across Akvo products.

Akvo sites are running on Wordpress, which has its own API (https://codex.wordpress.org/WordPress_APIs). So, hopefully, it will be possible to connect the tools via the future 'data format adapter' that will exist outside of Lumen.

**Comment by Lynngre** [comment]
@nadiagorchakova yes, I think we discussed this already re integrations/embedding & replacement of the plugins currently used. Not sure what the timeline would be on this but let me know when you're ready to look at it.

**Comment by janagombitova** [comment]
Work on this is paused for now. Once we pick it up again with Lynn we will open up an issue in the repository
