### ISSUE TITLE
Better organise Caddisfly test types 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-product-design#266]
Currently we have in Flow quite the long list of Caddisfly test types. We organised it by Water and Soil type, but as the list and diversity of tests will grow, we need to make the selection more clear and understandable to users. 

Secondly, we need to consider how purchasing Caddisfly will be implemented? Right now we have the Water module and the Soil module (the reason why the tests are lated the way they are). How will this growing list reflect the pricing groups? 

@mtwestra and Arthur will suggest what is the best way to group the tests based on their different types

![screen shot 2017-06-14 at 12 35 43](https://user-images.githubusercontent.com/12456965/27128239-04bd9c64-50fe-11e7-90f5-46da3b63f90e.png)

**Comment by arthurakvo** [comment]
Hi all. This is my first GitHub response ever :). Concerning the organisation of the Caddisfly question types I propose to make a split between soil and water testing and then subdivide it based on technology type. 

1. Soil Testing
    a. Test Strips
    b. Sensors
2. Water Testing
    a. Test Strips
    b. Sensors
    c. Colorimetry
    d. Microbiological

In this we don't bother soil users with water tests and vice versa. Moreover the subdivision based on technology type allows for a generic order that applies for different uses (drinking water, wastewater, agriculture etc.). If we would make the subdivision based on use there would be a lot of overlap between different tests.

@mtwestra @janagombitova what do you guys think of this order?

The full list for now would look like this:

1. Soil Testing
    a. Test Strips
          -Available Nitrogen (HACH 27454)
          -Available Phosphorus (Quantofix 91320) 
          -Available Potassium (MERCK 117985) 
    b. Sensors
         -Soil Moisture (Caddisfly)
         -Soil Electrical Conductivity (Caddisfly)

2. Water Testing
    a. Test Strips
          - Ammonium (Quantofix 91325)
          - Arsenic (Econo-Quick 481298)
          - Arsenic (0 - 4000) (EZ Arsenic High Range, HACH 2822800)
          - Arsenic (0 - 500) (EZ Arsenic High Range, HACH 2822800)
          - Chloride (Quantofix 91321) 
          - Chlorine, Hardness, Alkalinity, pH (HACH 2755250)
          - Free Chlorine (Akvo Caddisfly)
          - Nitrate - N & Nitrite - N (HACH 27454)
          - pH 4-9 (HACH 27456)
          - pH 0 - 14 (MERCK 1095350001 colorpHast)
          - Phosphate (HACH 27571)
          - Phosphate (Quantofix 91320)
          - Potassium (MERCK 117985)
          - Total & Free Chlorine (HACH 27450)
          - Total Iron (HACH 2745348
    b. Sensors
          - Electrical Conductivity (Caddisfly)
    c. Colorimetry
         1. Caddisfly Backcase
               -Fluoride (Caddisfly)
               -Residual Chlorine (Caddisfly)
         2. Lovibond MD610
               -....
               -......
    d. Microbiological
         -3M Petrifilm
         -Aguaenx CBT

**Comment by mtwestra** [comment]
@arthurakvo and @janagombitova, yes, this makes a lot of sense I think. We'll need to make sure that the striptests are easy to recognise in the UI, as there will be many, sometimes with more or less the same name.

**Comment by arthurakvo** [comment]
One other way we could organise the question types is as following: 
choose soil or water > select parameter > select device. 

By making the split between water and soil we directly eliminate most of the test the user is not interest in, by then choosing the parameter we prevent the creation of a very long list , followed by the technique/device a user needs. This would look as following: 

1. Water Testing
    - Ammonium
       -Test Strips
                -Quantofix Ammonium Test Strip (91325)
       -Lovibond MD610
              -60 Ammonia, Tablet (0.02 - 1 mg/l N)
              -62 Ammonia, Powder (0.01 - 0.8 mg/l N)
              -65 Ammonia LR, Tube (0.02 - 2.5 mg/l N)
              -66 Ammonia HR, Tube (1 - 50 mg/l N)
    - Arsenic
    - E.coli
       -Aquegenx CBT
       -3M Petrilm
    - Electrical Conductivity 
    - Fluoride
       -Caddisfly Backcase 
       -Lovibond MD610 
               -170 Fluoride, Liquid (0.05 - 2 mg/l F)
    - Total and Free Chlorine
    - Nitrate/Nitrite
    - pH
    -Phosphate
    -Potassium
     
2. Soil Testing
     -Nitrate
     -Phosphate
     -Potassium
     -Moisture
     -Electrical Conductivity 

Etc.
