### ISSUE TITLE
Improve geoshape editor in Flow app 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-product-design#267]
# Current situation 

*feedback from Joy* 
As we are increasingly using geoshapes there are some issues that as cropping up with its usability.
Generally Geoshape questions are very expensive for the project and add anywhere between 25-40% to the data collection time and is physically challenging as you will need to walk anywhere between 500-1000m on average. Most agriculture projects will benefit from geoshapes, but it needs to work better to increase acceptability.

## How do you create shapes? 

During the survey design the user decides which shape type should be captured for the question. The use is that only one shape is collected for one question. We have not experiences that more shapes are collected as an answers to one question (so no cases of: two and more shapes of the same type per questions, or two and more shapes of different types per question). 

Alphonso in the field does not make decisions on which shape type to collect. He maps out the area (for example) that is stated in the questions. He usually walks around the farm plot and captures his location as he goes. Sometimes the shapes are very large and then Alphonso moves around on a scooter. When he creates the shape he turns the screen off and comes back to the app as he relocates. We need to keep in mind that shapes are usually captured outside, can be in direct sunshine so the screen contract needs to be considered. 

Example cases for: points, line and area shape type? 

# Problem areas / Opportunities - WHY
We see the potential and application of this question type. The goal of this initiative is how can we make it easier for Aplhonso to use? 

## Saving the shape 
Currently you need to explicitly save a geoshape, unlike any other question type. This is problematic because if half way into the walk across the field, you inadvertently hit back or say the phone freezes (seems to happen more frequently than you would expect for geoshape questions), you have to start over again. 

## UI is unclear
**Select shape type** 
Before you can start capturing a shape you need to select the type, even if only one type is allowed If there are many shape types you can create per shape - you need to know that you need to pick the type first. Even if you have only one shape type, you need to pick it. The button is not so clear. I always want to start adding points to the map right away but can't as I have not confirmed my shape type 

**Map not zoomed in** 
automatic zooming - auto zooming the map to the correct scale once the user starts adding point. Currently it is difficult for the user to see the shape as it is being created. Zoom to such depths manually is pretty awkward on the phone (issue mentioned by Joy)

**Loose track of the order of points**
add a order number to each newly created point on the map. This is for the users to keep track on which point they added as last and create the shape they want. (Many times users loose track when creating complicated shapes and eventually end up with an odd shape, simply because they connected the wrong points - issue mentioned by Aulia)

## Empty shapes are allowed 
For mandatory geoshapes questions, if you do not provide any geoshape but just press save, you still get the message: "shape captured successfully" but there is not geoshape
https://github.com/akvo/akvo-flow-mobile/issues/745

## Validation of shape type is not in place
You can capture a line only even thought you have selected an area. This issue went quite far in the discussion on UI and validation. Here are two issues that touch upon this problem: https://github.com/akvo/akvo-flow-mobile/issues/366 and https://github.com/akvo/akvo-flow-mobile/issues/322

# How will we know this worked out? 

*to be agreed on* 

----- 
# Notes 

We need to know how we want the geoshape editor to ideally work and look like and then break down the changes to implementable and valuable pieces

**Comment by janagombitova** [comment]
Current UI in Flow's online page: 
<img width="784" alt="screen shot 2017-07-28 at 17 03 37" src="https://user-images.githubusercontent.com/12456965/28723368-d1f5d32e-73b6-11e7-8d61-fb88265941f3.png">

Simple example of the UI when creating a shape in the app currently: 

<img width="1066" alt="screen shot 2017-07-28 at 17 07 44" src="https://user-images.githubusercontent.com/12456965/28723585-81a55632-73b7-11e7-9a55-1f2351207dd2.png">
<img width="1065" alt="screen shot 2017-07-28 at 17 08 00" src="https://user-images.githubusercontent.com/12456965/28723586-830b4da6-73b7-11e7-80b7-6aae8c05a25a.png">

**Comment by janagombitova** [comment]
# Changes to consider: 

## On Flow's online workspace
1) In survey editor enforce only one share type per question
 - once the user selects geoshape question she must decide which shape type to capture. She can choose area, line or points. Only one shape type. 
- remove checkboxes selector and replace with UI element that enforces to only select one share type 

## In the app 
1) Ensure that shape type is already selected and Alphonso can start creating the shape type right away
2) Make sure that shape is validated: 
   - area type must have at least 3 points created on the map to be able to save 
   - line type must have at least 2 points on the map to be able to save 
3) simplify UI to resolve above mentioned issues

**Comment by valllllll2000** [comment]
@janagombitova not sure if this could work for us but how about having something like the running apps do. The running app will collect all the gps data as you run and then create a "path" for you, in that case Alphonso would just have to walk/run/drive and data would be collected for him automatically. Of course this may not be as precise as manually inputting the data.

**Comment by janagombitova** [comment]
@valllllll2000 I find that a very intriguing idea. We would need to test it out in the field to see if the accuracy is ok enough. But I do like it ;) It sounds as if it can resolve the issues partners have now, especially with having to save the shape and input each point themselves.

**Comment by janagombitova** [comment]
Issue moved to Flow mobile repo as we want to close this repository. Further discussions will happen there once we prioritise this work
