### ISSUE TITLE
Mark if data is open or private when uploading a dataset

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-product-design#272]
As @LarsSjogreen pointed out, Lumen users should specify at data import whether dataset is open or private. 

As an additional (not-mandatory) option, users could also specify data license type.
Possible options I found so far:

- Public domain
- PDDL 
- CC-0
- CC-BY 
- ODC-BY
- CC-BY-SA
- ODC-ODbL
- CC BY-NC-SA

But probably choosing between all those data licenses is asking too much from our users.

If a user marks dataset as open, it should be possible for everyone who has access to the instance to export it (when this feature is available) or share it publicly via a link.

If a user marks a dataset as private, there should be some constraints on how dataset is shared/exported.

The main point is to make users aware that managing data comes with responsibility.

**Comment by nadiagorchakova** [comment]
A comment from Karolina: if the data source is open, users should add where the original data can be downloaded from

This info should probably appear in meta data accompanying a data set

**Comment by Lynngre** [comment]
Wouldn't it be better to make it 'public' or 'private' at point of sharing instead of at import? Surely they wouldn't want to share their whole dataset as is, wouldn't they want to control which columns in the dataset are ok to be shared & which relate to the visualisation created?

**Comment by nadiagorchakova** [comment]
Good point, Lynn. I don't really know what users would prefer in this case, as we haven't talked to any of them about this feature yet.

**Comment by janagombitova** [comment]
As @nadiagorchakova mentions in her comment above that no user research on this opportunity has been done so far, I am closing the issue. Supporting our partners in handling data in a more responsible way is still one of the focus items we intend to pursue in the future. A new issue will be opened then
