### ISSUE TITLE
Save form version with form submission and show it

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-product-design#276]
# Context 

A survey form in Flow can have multiple versions as it is improved over the course of time. This can, however, result in the case when some devices have different versions of the form they are working with. If Alphonso gets the survey form to his phone in April and it is version 3 and goes offline for a month, he can capture data to the version 3 of the form even though Salim has already changed it to version 10. Once Alphonso goes back online with his phone to sync out the data, he also gets the updated version of the form, version 10, and captures more data with this newest version. 

# Why

Having multiple versions of a form can result in the end data to look different (answers missing as the question did not exist in version 3 but it did in version 4; different options in different submissions, etc). 

Usually our partners do now assign forms to devices until they are sure about the survey structure, but there are always cases when you realise that a question needs to be improved or changed once the data comes in. Some surveys can be used over a course of years. 

When looking at data the inconsistency in answers can bring confusion. Simply knowing that a submission is from version 3 and another is from version 56 of the same form can help clarify these inconsistencies.
 
In support when ours users point out issues with the submitted data, one of the 1st questions we ask them is to check which form version that device is running. It would be easier if we and our users could see that with all new submissions right away 

Ideally this information should be available for each new submission and shown when the user is previewing the data in the online space (Inspect data, Monitoring, Maps tabs) and when looking and working with the data in the exports. It would also be nice if in the app in the History view the user could see what the form version of that submission is, also for points she synced in and have this info available. 

# Next steps 

We should discuss the benefits and implications of such a change and see where indeed seeing the form version of the submission would bring the most value to our users, before we discuss implementation details. Let's talk @valllllll2000 @muloem @stellanl and @loicsans and @Kiarii 

I see this improvement as a part of making Flow more simple, clarifying the confusions and improving the exports. We can have this issue as a follow up to the initiative to improve the export structure of Flow data

**Comment by stellanl** [comment]
Strongly in favour. Complex data should always include version info.
It would also be good to retain an archive copy of each version of the survey. Since we already save it to S3 we could (also?) save it to a filename that includes the version.

**Comment by janagombitova** [comment]
App already saved the form version with submissions. Now we need to handle showing it in Flow and in Lumen. Issues created in the respective repositories
