### ISSUE TITLE
Support for admin boundaries in Lumen maps

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-product-design#278]
Lumen maps should support world admin boundaries as a separate layer in maps. This is one of the contractual obligations to the 9 country program.

**Potential sources of data:**

* GAUL http://www.fao.org/geonetwork/srv/en/main.home#boundaries
We can use it free of charge as long as we don't share the raw data itself and acknowledge GAUL somehow in the maps where their data is used.
The downside is that their data is a bit outdated - latest from 2015.

from Lars:
* Natural Earth has the most permissive license model. The problem is that they don't have information under national level in only a few countries so far. It might work for some uses, but not for all. http://www.naturalearthdata.com/

* Open Street Map seems to have quite a good coverage, especially in third world countries thanks to Humanitarian OSM. What is challenging there is to actually verify the source of data (and who decided what borders are correct or not). If we want to use that dataset, we have to be very clear that we rely on an open data submission process and we don't take any responsibility for the choices on how politically contested borders are represented. https://www.hotosm.org/

**It's unclear if..**

Do we need to support admin boundary data from previous years when an updated file with boundaries has been released? One of the use cases - data collection was done in 2015 and they want to preserve admin boundaries in their map as they used to be in 2015.

Should we allow users to choose between different data sources for admin boundaries?

Should we allow users to upload their own shape files with admin boundaries?

**Comment by janagombitova** [comment]
This has been handled with supporting uploading raster data files. All details can be found in this repo: https://github.com/akvo/akvo-lumen
