### ISSUE TITLE
Improve Comprehensive report 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-product-design#280]
# Context 
Current comprehensive reports consist of raw data + summary sheet. The Summary sheet calculates details and creates a frequency pie chart for option questions and number questions. The Comprehensive report is frequently used by our users to get a quick overview of the data captured to one form.  

# Opportunity 
Considering the high interest in this export type, the value it gives and can give and our current focus on improving exports in general, let's make it even more valuable.  

**HMW statement:** How might we give Petra and Salim a quick overview of all the data captured showing them some insights from the data without them having to do anything. 

# Why 
- users use the comprehensive report extensively to get a quick view of the data collected, to not to have to create graphs and charts on their own 
- current comprehensive reports are popular among users to get a quick overview of data 
- users want to grasp their data without too much effort and quickly 

# What 

## How can we improve what we have? 

We currently have summaries and pie charts for number questions and option questions. 

![screen shot 2017-10-25 at 11 31 56](https://user-images.githubusercontent.com/12456965/31991484-26d295a6-b978-11e7-8983-e837b5938b2a.png)

![screen shot 2017-10-25 at 11 32 21](https://user-images.githubusercontent.com/12456965/31991509-383bff9e-b978-11e7-85fd-3c05990bdf40.png)

## What can we add to make the report more valuable? 
- Which questions can benefit from having a chart and if yes, then which chart is the best? Which one are a no-go for visuals?  
- What are the other ways to summarize the data? 
- How the charts and graphs look in terms of design - editable so the user can adjust the size, chart type, colours, fonts, text, etc?  
- Besides summarising values, can we also give a total overview of the captured data? 

# Next steps 
* [x] remove the options to deselect summaries and/or charts - https://github.com/akvo/akvo-flow/issues/2284
* [x] get Karolina's view on best ways of showing summaries of answers for different data types (Flow question types) 
* [x] define new summaries for question types

**Comment by janagombitova** [comment]
From the chat with Karolina: 

We can not only look at summarising the data per question, but also giving a full data summary. Karolina brought in a perspective of someone who analysis data collected with Flow. She usually receives a data set and needs to do an in depth analysis to find patters and do projections based on the data. She goes outside of the boundaries of excel but with many data sets she does a quick look at the data to get a sense of it. Her feedback is based on what this quick look contains and on from her experience what are the basis people search for when looking at submissions to questions. 

# On the data collection itself 
It is handy for the person working with the data to get a quick summary of the entire data set. That can include: 
- number of submissions
- number of submissions per device
- number of submissions per user 
- min and max submission date 
- average duration 
- min and max duration

# On the data
**for all questions:** 
   - number of responses 
   - number of empty fields 

**option questions** 
- instead of pie chart create bar chart 
- counting frequency and percentage is good - can stay as it is

**number questions** 
- pie chart is a no go - needs to be removed 
- visually - can use a histogram which is a better option (x is the number and y is the frequency, numbers are put into buckets - of 10 for example)  
- counting frequency of how often a number value was submitted also not a good idea - remove
- percentage of the above frequency can be removed too 
- Min - ok
- Max - ok
- Mean - ok
- Median - ok
- Std Deviation - ok 
- Variance - ok
- Std Error - ok / can be removed
- Mode - can be removed 

**date** 
- min and max value 

# On the look of the charts
- can we remove change the design of the images? 
- remove the grey background and black frame? 
- use Akvo brand colours?  
- etc?

**Comment by stellanl** [comment]
About "On the data collection itself":
Are "number of submissions per device" and "number of submissions per user" meant as an average number or a list of counts? Like 
 * Device AA: 23
 * Device BB: 11
 * User A: 7
 * User B: 12

**Comment by janagombitova** [comment]
List counts - if that is possible, of course

**Comment by janagombitova** [comment]
Another point we need to consider for the data summaries is: **How might we distinguish and handle question answers that come from a repeated question group?**

**Comment by janagombitova** [comment]
Here are changes we can start with: 
* [x] remove pie charts for number questions 
* [x] remove the frequency counts and percentage for number questions 
* [x] add number of submissions in the beginning of the summary sheet

**Comment by janagombitova** [comment]
All completed for now, further improvements will be added as separate issues in the Flow repo
