### ISSUE TITLE
Improve on Flow online space notifications

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-product-design#285]
The online workspace has a number of notifications that are currently presented under the _Messages_ tab.  This is less than ideal because one has to visit the tab to see the notifications and to constantly refresh this tab every time there is a new notification.  This has to be redesigned to support push-style  notifications.

**Comment by janagombitova** [comment]
# Context 
As mentioned in the message above, a lot of notifications are shown to the users in the Messages tab. These notifications inform the users about tasks Flow runs in the backend and if they succeed or fail. The Messages tab is a separate tab in Flow. The messages are currently organised in a table with the latest message on the top.  

![screen shot 2017-12-21 at 10 54 02](https://user-images.githubusercontent.com/12456965/34250540-6bcae11c-e63d-11e7-9c53-7b07091739f0.png)

## Why? What is the purpose/value? 

Some tasks take long to complete in Flow and thus to not have to have the user stuck on the page waiting, we allow him to do other tasks while Flow is completing the other one. Once done the user is informed. 

## Who? 

The users looking at the messages are the ones running the tasks the messages show for. So it is usually Salim or Petra after finishing a survey for data collection, or a cascade, or when importing in data etc. 

## What tasks take longer to complete but Salim needs to know the result? 
This list does not imply that these tasks are now handled by the Messages tab, or that they should be handled by the Messgaes tab. They are just to list down actions where the direct feedback is not so direct in Flow currently. Here is the list:  
- publishing a survey to make it available to send to devices 
- copying a survey 
- (moving a survey is shown directly in the UI with the loading spinner to indicate progress)
- manual survey transfer (you get an email with the survey file) 
- bulk upload data 
- getting a data export out of Flow 
- importing in data via data cleaning (either cleaned data or new data) 
- publishing a cascade 
- importing a cascade 

## Current issues 

This set up has many issues: 
- we only show 20 messages so the user cannot see older messages
- we combine many different messages in one list that makes it hard to find what you are looking for and hard to orientate 
- the language is very technical and users to do understand what things mean 
- some messages are of no value to users 
- some messages are placed on this list even though it would be more helpful for users to see them right away after completing the task - especially the error messages
- the user has no way to know he has a new message if he is in a different part of Flow 
- to see if there is a new message when being in the tab, Salim has to navigate away from the tab and come back, or refresh Flow fully 

## What messages we currently show in the messages tab? 

What | Type | Current message | Useful to users? 
--- | --- | --- | ---
Every submission made from an device connected to the instance | fileProcessed |[zip file ID].zip processed - Surveys: [form ID] | no 
Bulk upload data | fileProcessed |[zip file ID].zip processed - Surveys: [form ID] | no 
Bulk upload data | bulkUpload | File: [zip file ID].zip processed | yes
Copying survey completion | copySurvey | Copying from Survey 232429116 (1.9.26 all questions) completed | yes
Publishing of a survey is completed | surveyAssembly | Published. Please check: [urls to the xml file]  | yes
Failed to import cleaned data | importData |  Invalid RAW DATA file: [file name] - [error] | yes
Data cleaning import completed | spreadsheetProcessed | Spreadsheet processed | yes
Failed to import in new data via data cleaning | importData| Invalid RAW DATA file: [file name] [error] | yes
Success to import in new data | spreadsheetProcessed | Spreadsheet processed | yes
Importing a cascade | cascadeImport | Successfully imported csv file [file name] | yes
Publishing a cascade | cascadePublish | Cascade resource [name] - Cascade successfully published | yes

# Opportunity 

## Things to consider: 
- Is the Messages tab the best way to communicate? 
- Which messages follow under the category - take long and we need to see how to inform the user without limiting him? 
- Which messages should be shown right away in the page where the Salim did the task? 
- What information is helpful for the user to see? 
- What things do we inform about via email and is this ok in regards to data security and privacy? Should these move to messages or somewhere else? 

## Guiding principles
- easy to orientate in the different message types 
- easy to find the latest one 
- easy to understand what the message is about and what it relates to 
- easy to know I have a new message 

# Related issues 

We have decided to show errors when importing in a cleaned data sheet or new data via data cleaning directly in the page and not in the messages tab. Thus there messages will be removed from the messages tab and shown in Data cleaning. See issue here: https://github.com/akvo/akvo-product-design/issues/286

**Comment by janagombitova** [comment]
Linked to issue in Flow's repo
