### ISSUE TITLE
Formula-based validation and display conditions

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-product-design#36]
### Overview

The aim is to introduce validation and question display conditions based on formulas. This will provide much more flexibility in validating questions, and deciding if a question should be shown.

At the moment we only have very limited validation, mainly setting limits on number questions. 

The functionality will include:
- a validation condition and display condition on all questions
- validations can span multiple questions (if 'yes' was answered on question 1, and the answer to question 2 is larger than 15, don't validate, and display 'value too high')
- a formula editor with which (simple) formulas can be edited
- A configurable message that is shown when a validation does not pass 

The validation condition can include a 'format-check', for example if the format corresponds to the format "xxxx-yyyy-zz",
### Links to documents

https://github.com/akvo/akvo-product-design/blob/master/FLOW/Features/36-FormulaValidationDisplay/FunctionDesign.md
https://github.com/akvo/akvo-product-design/blob/master/FLOW/Features/36-FormulaValidationDisplay/VisualDesign.md
https://github.com/akvo/akvo-product-design/blob/master/FLOW/Features/36-FormulaValidationDisplay/TechnicalDesign.md

**Comment by janagombitova** [comment]
Issue is moved the Flow repo here: https://github.com/akvo/akvo-flow/issues/2861 as part of cleaning us this repository
