### ISSUE TITLE
Display-text question type

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-product-design#38]
### Overview

The aim is to introduce a display-text question type. This is a question without an input field, which is just used to communicate things to the enumerator, optionally based on his/her input.

The feature will include:
- the user can select a 'display-text' question
- the user can supply a formula-based display condition
- the user can customise the text shown using the output of another question, including a computed value question. 
### Links to documents

https://github.com/akvo/akvo-product-design/blob/master/FLOW/Features/38-DisplayTextQuestionType/FunctionDesign.md
https://github.com/akvo/akvo-product-design/blob/master/FLOW/Features/38-DisplayTextQuestionType/VisualDesign.md
https://github.com/akvo/akvo-product-design/blob/master/FLOW/Features/38-DisplayTextQuestionType/TechnicalDesign.md

**Comment by janagombitova** [comment]
Copy of the issue exists here: https://github.com/akvo/akvo-flow/issues/2608
