### ISSUE TITLE
RSR API for general data input

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-product-design#39]
It's becoming more and more apparent that RSR needs a full-fledged CRUD API. Currently we have a read-only API that covers most of the data, and a custom solution for loading IATI-formatted data, turning them into projects.

Several parallel developments point at the need for an API that fully supports all HTTP verbs to enable the use of RSR as a service among many other services.

**Comment by adriancollier** [comment]
More work needs to be done on the permission of this feature.

Relevant user stories (https://trello.com/b/ttv77ac1/rsr-user-stories):
- As an authorised tehcnical member I can create and publish valid projects (# 220)
- As an authorised technical member I can create and publish valid organisations (# 221)
- As an authorised technical member I can edit projects and organisations (# 222)
- As an authorised technical Member I can manage the content for my organisation and the organisations that belong in my organisations network (# 276)

What is missing is the correct permissions access to allow for projects and organisations to be effectively managed through the API without granting full permissions to the user.

**Comment by nadiagorchakova** [comment]
Gabriel says the issue is not relevant any more. The API is fairly close to fully general now
