### ISSUE TITLE
Display of filled forms and data points

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-product-design#44]
The aim is to implement a way to display both incoming filled forms, and full data points with multiple forms, in a way that makes sense to the user.

**Comment by mtwestra** [comment]
Needs to be part of the 'how to represent / show / export data' conversation

**Comment by janagombitova** [comment]
Same as #100

**Comment by janagombitova** [comment]
Closing issue as this work is part of #100 and #70
