### ISSUE TITLE
FLOW App external data sources question type - Caddisfly Question

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-product-design#5]
Android phones are capable of many things beyond taking a GPS reading and a photograph. Multiple organisations are creating specialised apps, sometimes with extra hardware attached to the phone, to do a range of measurements, such as distance, vibration, sound level, angle, water quality, and others.

This feature will enable Akvo FLOW to use measurements from such devices as part of the regular survey work flow.

As a first implementation, we create a link between Akvo FLOW and the Caddisfly water quality app of our partner Ternup (http://ternup.com/) 
### Links to documents

Functional design document:
https://github.com/akvo/akvo-product-design/blob/master/FLOW/Features/5-AppExternalDataSources/FunctionalDesign/AppExternalDataSources.

Technical design document:
https://github.com/akvo/akvo-product-design/blob/master/FLOW/Features/5-AppExternalDataSources/TechnicalDesign/AppExternalDataSources.md

**Comment by mtwestra** [comment]
1) FLOW Dashboard -> FLOW App
What we need to introduce:
* FLOW users need a way to specify that a question is a Caddisfly question
* FLOW users need a way to select which test type will be done by Caddisfly. The idea is to have a two-step presentation of the information, either through a double drop down, or by a more elaborate user interface. The top level ordering is the type of test: Air quality, Water quality, Soil, Food. The next level is the actual tests, with information on the full  name, producer, the range, etc. This information should be available in multiple languages.
* To communicate the test type to Caddisfly, we need a naming convention for the tests. For example something like “STRIP-HACH-CHLORINE-27450” and “SENS-SODAQ-EC”, so a combination of the type of test (STRIP for strip, SENS for sensor), the producer of the sensor (HACH, SODAQ), etc.
* The name of the test is embedded in the survey definition XML file as a property, for example “type=“STRIP-HACH-CHLORINE-27450””.
* Each patch will also need a separate definition and name.
* In order to store the type definitions, we could create a Java class holding the definitions. 
* In order to be able to process the incoming data later, which will be in the shape of a json map with property/value pairs, we need to know for each test which properties we expect to get back - we need the schema of the expected answer. This could perhaps be done as an array of strings and types.

2) FLOW App - Caddisfly app
On the FLOW app, the user fills in a survey. On the caddisfly question, a button ‘perform test’ can be pressed. After this, the FLOW app sends an intent to the Caddisfly app, containing the test type mentioned above.

3) Caddisfly app -> FLOW app
* On the Caddisfly app, the test is performed. This leads to a set of data that contain multiple properties, and multiple images. The data is encoded in a JSON response to the FLOW app.
* One question is how to deal with images. There are two posibilities: 
	
1) embed the image data directy in the resulting json response, in base64 encoded form. A single image will be about 25k, and we can have up to 10 images, so for a total of 250k per response. For example: {type:”STRIP-HACH-CHLORINE-27450”, ts:4463736473, patchVal1:32.2, img1:eyHS443SDJ….D34TWS, patchVal2:10, img2:ey837466...DHWYH76SS88S}
	
2) Treat them as separate images. The response would then only contain a uuid for the image name, and the Caddisfly app would need to put the images in the FLOW external directory, where they can be picked up. For example: {type:”STRIP-HACH-CHLORINE-27450”, ts:4463736473, patchVal1:32.2, img1:E003F608-9F37-11E5-98D1-197109FBD261, patchVal2:10, img2:D7FDB958-9F37-11E5-AE15-197109FBD261}

**Comment by janagombitova** [comment]
#### For the 1st implementation - to be done:
* [ ] create the option to select a Caddisfly question type and specific test when creating a survey 
* [ ] create a direct communication between FLOW app and Caddisfly app - user click on action button in FLOW app that opens directly the selected test in the Caddisfly app. If Caddisfly app is not installed, a warning message is shown  
* [ ] show the Caddisfly result in FLOW dashboard (in Data tab and Map tab, Charts subtab) 
* [ ] Caddisfly results in FLOW Excel reports  

https://github.com/akvo/akvo-flow/issues/1570

**Comment by janagombitova** [comment]
With the Jubilant Jaguar we have release most of the Caddisfly-Flow integration implementation. The missing parts is the data export as there were some problems found during the testing, with (1) exporting the data, (2) data cleaning now working at all. These fixes are planned for the next Flow release (end of November)

Regarding the **Follow up steps** we need to: 
* [ ] collect information on users using the "old" implementation
* [ ] create steps that they need to take to switch to the new implementation 
* [ ] test the steps that nothing breaks
* [ ] create communication around this with an end date tied to a release (remove old code) + make sure you add a note to change API set up
* [ ] communicate this with the relevant partner team members
* [ ] communicate via partner team with the partners and give them a time frame to make the switch  
* [ ] remove old code in one of the 2017 releases (make sure the feature flag is out as well and removed from dashboard build)
* [ ] release 
* [ ] communicate to partners that change has happened and the old implementation is no longer available

**Comment by janagombitova** [comment]
Caddisfly in now fully functional on all parts of Flow. How we will proceed with removing the old 5 code Caddisfly question type will be handled in a separate issue
