### ISSUE TITLE
Paperless Reporting

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-product-design#6]
### Overview
In order to make RSR more useful to our partners, we need to extend the existing functionality in order to accomodate tracking of progress of information about projects over time.

This also more closely aligns the data set of RSR with the IATI Standard.

We will be adding Time values to both the Budget and Indicator sections of the data sets.
We will also be including Transactions in the data set. Transactions indicate funds that are sent from the Project Overall Funding to Individual Organisation.
Transactions differ from Budgets as the Transactions indicate funds are with the Partner responsible for the spending, while Budgets indicate the amount of money that is available to spend in the Project, OR the amount of money that has been spent while undertaking the Project.

Changes to Indicators may be delayed due to upcoming confirmation on Indicator structure that will be discussed in the IATI TAG Conference in Montreal 29-30 January 2014.

### Links to documents

Functional Design Document:
https://github.com/akvo/akvo-product-design/tree/master/RSR/Features/6-PaperlessReporting/FunctionalDesign

IATI - RSR Comparison and Requested Changes created by Akvo Partner Team:
https://www.dropbox.com/s/qam2njzrq5row0e/IATI%20%E2%80%93%20RSR%20extra%20features.pdf

Github Issues:
https://github.com/akvo/akvo-rsr/issues/231

**Comment by kardan** [comment]
I updated the link to the directory so one can look at the existing docs.
