### ISSUE TITLE
Introduce Mobile users

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-product-design#60]
The aim is to introduce mobile users on the device. The purpose is to have a better control over who has access to what information, and to not be dependent anymore on recognising devices.

Preliminary ideas:
1) Mobile users will login to the device
2) They can be added in bulk in the dashboard
3) a 5-number pin code will be used for access
4) on the phone, two types of user exist: enumerator and device admin
5) users can create a new account on the phone, and send it to the dashboard. There, users can be approved
6) the device admin can create new users ad hoc on the phone, offline.
7) if a user forgets his/her pincode, it can be reset in the dashboard, or by the device admin

Assignments:
1) under the user tab, there will be a facility to couple forms to users.

**Comment by janagombitova** [comment]
Issue handled in Akvo Flow's mobile app repo
