### ISSUE TITLE
Custom reporting

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-product-design#65]
Functional Design: https://github.com/akvo/akvo-product-design/edit/master/FLOW/Features/65-custom-reports/FunctionalDesign.md

**Comment by mtwestra** [comment]
This was preliminary work for FLOW, that needs to be incorporated in DASH thinking

**Comment by janagombitova** [comment]
We have implemented the ability to export Lumen visualisations and dashboards. With Flow data is exportable. With the Flow and Lumen integration not only both values will be available to all our users but we also need to take the thinking on how data is actually used further and based product decision on the new strategy and learnings and assumptions we have. Thus closing this issue
