### ISSUE TITLE
Improve current reports

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-product-design#71]
The aim is to improve the current reports, with special focus on:

* monitoring
* lat/lon geoJSON
* repeated question groups
* other packed formats, such as barcodes

**Comment by mtwestra** [comment]
Suggestion by Steen:
http://flowhelp.akvo.org/discussions/problems/3374-akvoflow-export-of-data

The suggestion is to split option questions with multiple options in columns, with one column for each option. There could be a yes/no, or 1/0 encoding for absence/presence of an option in a column.

**Comment by Steen-Andersen** [comment]
However, the advise on splitting one column to many in Excel CANNOT be used.
It works if you ALWAYS have the same number of entries in the same order but in our case the entry will be mixed - see this example:

Depending on the number of crops, these are listed in column 1,2,3 and mixed!
 
We need one column for each available option!
 
![crops](https://cloud.githubusercontent.com/assets/9528094/6107100/93aaf530-b078-11e4-82e1-f3b7b30c71c5.JPG)

**Comment by muloem** [comment]
Another request for coding options: http://flowhelp.akvo.org/discussions/problems/3386-fwd-snv-wash-impact-study

**Comment by janagombitova** [comment]
This issue is related to https://github.com/akvo/akvo-product-design/issues/130. Will add the information to the document linked to the mentioned issue, so we tackle both and all at once.
