### ISSUE TITLE
Mandatory usage of GPS information in EXIF

### ISSUE THREAD

**Issue by bjelkeman** [akvo/akvo-product-design#74]
# Overview

We have a requirement for automatically using the GPS information available in the photo image file when available. This would be extracted from the EXIF format, using a standard function.

## Benefit

Increased trust in the data created by the enumerator, where the photograph has the same or very similar GPS information as the manually added GPS location in a survey. (Manual mening click the GPS button in the survey.)

## Expected feature

* Warn the user if the phone does not automatically add GPS information to any photograph taken or added with the FLOW application (probably a small warning sign, red when not available and green when ok)
* Automatically take the GPS information stored in EXIF and add it to the survey (in a similar fashion that the time taken to perform the survey is added to the data)
* Warn the user if the GPS data from the photograph is significantly different than the manually added GPS location in the survey. (Manual mening click the GPS button in the survey.)
* An easy way to in the dashboard see which data point has GPS data which differs from the EXIF GPS data, or does not have EXIF GPS data. 

(Moved from [FLOW mobile repo](https://github.com/akvo/akvo-flow-mobile/issues/260) )

**Comment by ichinaski** [comment]
The two approaches we discussed last week for serialising the location are:

* Use image's EXIF metadata: Convenient way of packing location information in a standard way. Drawback is that the dashboard would have to fetch the image from S3 in order to parse and display the location in the preview/reports.
* Update response format: Use JSON for image responses, storing the image URL and location. The location is immediately available in the datastore, at the cost of introducing format inconsistencies for existing data, and components that need to treat compound responses in a special way (i.e. datapoint name computation)

**Comment by janagombitova** [comment]
### Implementation suggestions (from the user perspective): 

**Dashboard - Survey creation**
- Geotagging of photos should **not** be mandatory, as this is not something every user requires
- add a 'Setting' to the photo questions > checkbox "Geotag - Add geographic coordinates to photo"
- Photo question type will still not be supporting the option to be used either as data point name, nor data point location, dependency remains supported

**On the app**
- under the question name and above the photo button add sentence warning the app user that this photo will be geotagged: "Geographic coordinates will be added to this photo." 
- once the photo is captured, saved and shown in the app in the form, under the photo show the captured geographic coordinates: latitude, longitude, elevation 

**Viewing the submitted form > photo in the Data tab**
- under the photo url show the captured location: latitude, longitude, elevation 

**Viewing the photo in the Map tab**
- for current maps: under the photo url with the 'open photo' link show the captured location: latitude, longitude, elevation 
- to actually show the location photo on the map will be handled in a following implementation (suggest to reuse the UX from geoshapes - needs further design and discussion time) - https://github.com/akvo/akvo-product-design/issues/132

**Report** 
- additional columns holding the geographic data: photo url, latitude, longitude, elevation, geocode (?)  

@ichinaski @muloem @jonase @mtwestra What do you think?

**Comment by joycarpediem** [comment]
I think it will add a lot of value to show the distance between gps value of the data point and that of the photograph. Otherwise this additional location data will be difficult to use.

**Comment by ichinaski** [comment]
Some remarks on @janagombitova's suggestion:

**Dashboard - Survey creation**

* I'm not sure about this step. This information should not be enforced by the survey definition, but rather automatically included **if available**. Each flag we add to the question is just an extra complexity the user has to deal with. Also, we don't have any kind of API versioning in place. We should not modify our serialization formats so often.

**App**

* Geolocation is not always available. We should add it if possible, but don't consider it something mandatory, as this would complicate workflows and drain battery unnecessarily.
* Showing the details of the location in the app sounds a bit explicit. Original suggestion by @bjelkeman was less intrusive (short text and/or icon indicating the presence of GPS data).
* If the location is not known by the time the form is over, I would not disallow the user from submitting the form. The way I was thinking of this feature was as follows:
    * Receive photo from camera app.
    * If the location is known, attach it to the EXIF, and show a (small) success message.
    * If the location is unknown, add a (small) warning.
        * (Optional) Asynchronously listen for the location and update the EXIF info whenever is ready.

**Comment by iperdomo** [comment]
> * If the location is unknown, add a (small) warning.
>  * (Optional) Asynchronously listen for the location and update the EXIF info whenever is ready.

As a user if i see a warning message/icon i get worried about it. Shouldn't this be transparent to the user? Remember that we're dealing with non tech savvy people.

**Comment by janagombitova** [comment]
Update based on discussion from 09 Dec with @bjelkeman, @joycarpediem, @muloem, @ichinaski and myself: 

### Problem we are addressing with geotagging in photos:
To assure data quality and that photos are taken within the location they are to refer to. As all our data is geo-referenced the question came up: How do I know that the photo was taken for sure at that location? In many cases the information given by the photo is vital for programmes and proof that these images are in fact correct needs to be given.  

### Decisions - 'visible to the user'
- we will **not** add another setting on the survey definition level, which will allow the user creating the survey to decide whether they want their photos to be geotagged or not. This is to limit the amount of decisions our users have to make.Thus every photo will by default be geotagged (if GPS information is available on the device).
- if the app user does not want his location to be captured, this is a decision he can make by changing the general device settings. No additional settings on the app are needed. Considering FLOW is an application used by organisations who want their information to be geographically referenced, this should not be an issue (based on input from the field). 
- the process of geotagging will happen automatically in the app either by reading the location information stored in the EXIF of the photo, or if not available in EXIF then captured directly by FLOW (@ichinaski will share the technical details and issues we need to solve first, before being able to implement this feature) 
- a subtle indication will be shown on the app to the enumerator, that the photo is geotagged or not (needs design input) 
- if a photo is not geotagged, a form can still be submitted
- on the dashboard when **viewing the submitted data** and in the **reports** we will indicate whether the photo was geotagged or not. If geotagged the distance from the location of the data point will be given by default and potentially also the GPS information of the photo (this still needs to be decided upon)
- how geotagged photos are shown on the **map** will be dealt with in later implementations as this needs further design and UX review

**Comment by muloem** [comment]
I would go as far as to ask why we have a geo question type at all. Since we want to geo reference the data (photos, surveys etc) as long as there is a GPS signal and its enabled on the device, we should perhaps not even ask the enumerator to fill in this data but just infer it and append it without user intervention.  The supervisors would know that GPS data can never be entered manually and combining location with survey time should give a fairly accurate image of whether or not data collection is being faked.

**Comment by mtwestra** [comment]
I don’t agree. The geolocation is something that should be taken deliberatly, for example by checking the GPS quality, standing somewhere for a while. Say you do a survey of a well. In that case, you for the geo question, you want to walk up to the well, and take the reading. The photo might be taken from 10  meters away. And the rest of the survey might be conducted somewhere else entirely.

**Comment by janagombitova** [comment]
If we agree not to change the way location of the data point is captured, but we do capture the location of each photo taken (if available) then on the dashboard side of FLOW we can reuse the pattern applied for geoshapes on the dashboard: 

**- In the Data tab:** - currently we show a link for the photo
   - I see two options here: 
      - A. under the image link add the location information (lat and long) and next to is a action button "Show on map". Once clicked on a map will open below and render a point for the data point and another for the photo location and the "Show on map" will change to "Hide map" 
      - B. under the image link show by default a map with the location of both data point and image 
   - indication of the distance from the data point location (if existing): Distance from data point: 5m 
   - if there is no location captured for that photo, then a sentence saying no location captured (same as will be used in the app to inform the user if the location is or is not captured) below the image link

**- In the Map tab:** #132
   - in the side bar we render the image and below photo we should indicate the distance from the data point (as in the Data tab) 
   - below the image, aligned on the right, next to the Distance the action button "Show in map / Hide from map" which will add a blue point on the main map if selected (same behaviour as with geoshapes)
   - I was thinking of also adding a small map in the side bar as with geoshapes, but I am not sure it will provide so much value as it will only hold one tiny point in it, plus it will make the scrolling through all the answers much longer. If the user clicks on "show on map" then the main map should by default zoom in to the location of the photo.  
   - if there is no location captured for that photo, then a sentence saying no location captured (same as will be used in the app to inform the user if the location is or is not captured) under the photo (in place of the distance and action button) 

**- In the raw data reports** - Will we indicate that a photo was geotagged in reports? If yes, how and what information will be provided?

**Comment by ichinaski** [comment]
We should take into account that images are not stored in FLOW's datastore, but in Amazon S3.

Computing the distance every time the data tab is requested, and sequentially processing each file (one image at a time) may be highly inefficient and time consuming.

**Comment by mtwestra** [comment]
One proposal would be to let the app return a JSON object which includes the image URL, and any geolocation, such as: {name:8D5ACA72-C4D4-11E5-B9B9-73A1531BF5E9.jpg, lat:52.3388374, lon:4.388374}. In that way, the location can be shown on the map, as well as be rendered in a list in the data tab. 

The principle would be: all the data about something needs to be in FLOW, including metadata about an image.

**Comment by ichinaski** [comment]
From Skype:

If we take that route now, we should thoroughly review:

* App format incompatibilities -- I have this under control
* Dashboard visualizations -- Handle both formats. Never take JSON for granted. Disable edits?
* Reports -- Handle both formats. Never take JSON for granted. Disable edits?
* Datapoint sync API -- Always return raw value. Not JSON

Anything I'm missing?

**Comment by janagombitova** [comment]
When it comes to the proposed dashboard implementation (see comment above) we should also consider how RSR shows location of photos on the map http://rsr.akvo.org/en/project/3811/update/14432/#
![screen shot 2016-03-04 at 16 51 42](https://cloud.githubusercontent.com/assets/12456965/13531988/8efacea0-e229-11e5-976a-ba54ca46f95b.png)

**Comment by muloem** [comment]
#### Notes from requirements review for geo tagging on the dashboard

First of all, the main driver behind geotagging photos is to provide a field managers the ability to perform quality control checks on the data collected.  (in this case on images taken).  The initial step in this work has been to include geo location information in the exif data of the images.

Next issues to tackle are proposed as follows:
* we will serialise the geolocation data of an image into the image response (JSON formatted) sent to the dashboard. in addition we need to include an *accuracy* parameter for the image geo location data

* Under the inspect data tab, we propose to show the image URL as is shown at the moment and underneath that show the geolocation data of the image, as well as a calculated distance between the associated data point location and the image geolocation

* Under the maps tab, when a particular data point is selected and has geotagged images associated with it, we will display the pins for the image location and if one clicks on the pin we display the associated image.

* The image point display on the map will first be addressed under CartoDB maps and if possible for the normal maps as well

* Generated reports will include the geolocation of an image as well as the calculated distance between the image and the data point location

* We will support both the image URL and the JSON formatted response formats for images to handle backwards compatibility

@Kiarii @loicsans @janagombitova @kymni @ichinaski please look through and give feedback if any. thanks!

**Comment by janagombitova** [comment]
@muloem No comments for now. @loicsans and @Kiarii I have written down the user stories for this feature as we had them 'here and there'. You can find them all summed up in this doc to give you more insight on the needs. https://docs.google.com/document/d/1pFKNdT0QrCOt5RDdq42i72_bQ3WHHJy1xxcUw1fc5Zw/edit

**Comment by janagombitova** [comment]
**Separate implementation steps based on the above mentioned comments:**
* [x] app captures the geolocation (from exif or independently) https://github.com/akvo/akvo-flow-mobile/issues/402
* [x] dashboard reads the geolocation data and accuracy https://github.com/akvo/akvo-flow/issues/1527
* [ ] display geolocation information in Data tab under the image and video url 
* [ ] add location data to reports 
* [ ] show geolocation on Maps 
* [ ] calculate the distance between the datapoint location and the image location
* [ ] display distance information in Data tab
* [ ] add distance information to reports 
* [ ] show distance information on maps

@muloem Can you please review and make changes if needed? Thanks

**Comment by ichinaski** [comment]
As discussed with @loicsans and @janagombitova , the easiest way to go about the geolocation display is to add the lat/lon information in the existing layout. In the dashboard, this means adding this information in the *Inspect Data* tab, whereas in the reports, we can add it to the existing cell.

**Comment by janagombitova** [comment]
1st implementation deployed in 1.9.9 dashboard version and the following steps are handled in another issue
