### ISSUE TITLE
Resposes coding

### ISSUE THREAD

**Issue by fnwarui** [akvo/akvo-product-design#75]
We have been receiving several request if FLOW can allow one to code responses . Example if I have a question with an option YES/NO, the system should allow me to Code YES=1 and NO = 0 such that if I choose YES it will input 1 and if I choose NO to input 0 and when I download the raw data the yes and No will not show but 1 and 0 will show instead.

**Comment by muloem** [comment]
Closing.  This request has already been mentioned in #71
