### ISSUE TITLE
Single FLOW App

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-product-design#79]
The goal is to create a single FLOW app, as a replacement for the current system in which an app is created for each FLOW instance.

Documents:
https://github.com/akvo/akvo-product-design/blob/master/FLOW/Features/79-singleFlowApp/FunctionalDesign.md
https://github.com/akvo/akvo-product-design/blob/master/FLOW/Features/79-singleFlowApp/TechnicalDesign.md

**Comment by ichinaski** [comment]
From Skype:

One possibility, not only for image responses, but in general, is to get the responses format right from the beginning with the single app, which would require an install from scratch. I somehow see this as an opportunity to introduce otherwise disruptive changes

**Comment by janagombitova** [comment]
Copy of this issue is here: https://github.com/akvo/akvo-flow-mobile/issues/1179
