### ISSUE TITLE
JSON serialization

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-product-design#80]
# Overview

The *Tab Separated Values*(TSV) legacy format has become something very cumbersome to deal with. At least when it comes to FLOW features extensibility: appending new columns to the CSV file is getting fairly unmaintainable. Furthermore, there are several columns no longer in use, but they cannot be removed from the serialization approach, for they will break the format structure.

The long-term approach to fix this problem is to use a more versatile JSON format.

# Documents:

* [Functional design] (https://github.com/akvo/akvo-product-design/blob/master/FLOW/Features/80-json-serialization/FunctionalDesign.md)
* [Technical design] (https://github.com/akvo/akvo-product-design/blob/master/FLOW/Features/80-json-serialization/TechnicalDesign.md)
* Visual design (TODO)

## Update (21/4/15):
 In order to take one step at a time, we'll break down this milestone into smaller issues. The first goal will be to replicate the current data format, using JSON. This will give us a solid ground and generic case to extend the feature further. Subsequent issues will deal with individual response types and the implications they'll have in the datastore management.

**Comment by ichinaski** [comment]
I'll write this down as a comment rather than a feature description point, but since all the responses will already be serialized into a JSON string, we might want to leverage this resources when it comes to syncing datapoints (no need to recompute the whole set of responses from the GAE datastore, which is highly inefficient right now). I'm not yet sure about the best and most efficient way to potentially store this data, but it could be something to consider.

**Comment by mtwestra** [comment]
@ichinaski I see what you mean, but this data might be changed due to data cleaning, so will need to be  recreated?

**Comment by ichinaski** [comment]
@Mark Good point. There's unfortunately not guarantee that the JSON responses are up-to-date...

**Comment by ichinaski** [comment]
Sample schema based on current data (irrelevant columns have been removed):
```json
{
    "title": "Form Instance",
    "type": "object",
    "properties": {
        "formId": {
            "type": "string"
        },
        "formInstanceId": {
            "type": "string"
        },
        "datapointId": {
            "type": "string"
        },
        "deviceId": {
            "type": "string"
        },
        "username": {
            "type": "string"
        },
        "email": {
            "type": "string"
        },
        "submissionDate": {
            "type": "integer"
        },
        "duration": {
            "type": "integer"
        },
        "responses": {
            "type": "array",
            "items": {
                "title": "Response",
                "type": "object",
                "properties": {
                    "questionId": {
                        "type": "string"
                    },
                    "answerType": {
                        "type": "string"
                    },
                    "value": {
                        "type": "string"
                    }
                }
            }
        }
    }
}

```
