### ISSUE TITLE
Visualize non-published cascades

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-product-design#93]
### Overview

Currently when the user decides to select an existing cascade in the cascade resource tab, there is no indication on which of these cascades are published and which are still in the editing state. Secondly, when the user selects a cascade while creating a new question in a form, the cascades which are not published yet are not listed in the dropdown, what creates confusion among users. 

We need to create a visual cue to indicate the “editing” status to the user in the Cascade resource tab and when creating a Cascade question. 
- In the question creation, an idea is to show the full list of all cascades and distinguish the non-published ones as grey. When creating a new question, the user will not be able to select the grey cascades. 
- In the list under Cascade resource tab, there will be a visual indication showing the difference between published and the ones still in “editing” state. 
### Links to documents

Links to the functional design documents
https://github.com/akvo/akvo-product-design/blob/master/FLOW/Features/93-VisualizeNon-publishedCascades/FunctionalDesing.md

**Comment by Kiarii** [comment]
Mockup wireframe of cascading resource status visualization in the dropdown selections:

![cascade state visualized](https://cloud.githubusercontent.com/assets/12692444/8546739/d6a9c398-24c2-11e5-9942-a8021f398a90.png)

**Comment by muloem** [comment]
I like this a lot @Kiarii. One question, are we also going to use colours as cues? e.g red or green or maybe thats not necessary?

**Comment by Kiarii** [comment]
@muloem I did consider using color codes but I thought that they would increase the color usage in the interface; we already at least 6 colors in the survey creation/editing page, in addition, color codes would require a textual key - (Draft/Published) seems simple and straight forward..

**Comment by muloem** [comment]
@Kiarii understood.  that sounds logical!

**Comment by janagombitova** [comment]
Duplicated here https://github.com/akvo/akvo-flow/issues/1309
